metadata:
    name: sleep
    format: "Lava-Test Test Definition 1.0"
    description: "sleep test plan"
    maintainer:
        - ktouil@baylibre.com
    os:
        - openembedded
    scope:
        - functional
params:
  test_params: ""

run:
    steps:
        - ./config/lava/sleep/sleep.sh ${sleep_params}
