repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-executables-have-shebangs
    - id: check-merge-conflict
    - id: check-yaml
      exclude: config/rootfs/debos/rootfs.yaml
    - id: check-toml
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  - id: black
