#!/usr/bin/env python3
#
# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2022, 2023 Collabora Limited
# Author: Guillaume Tucker <guillaume.tucker@collabora.com>

"""KernelCI Command Line Tool

This executable module is the entry point for the kci command line tool.  It
provides a way to manually interact with the KernelCI API and its related
features.  See the online documentation for more details:
https://kernelci.org/docs/api/.
"""


from kernelci.cli import kci
from kernelci.cli import (  # pylint: disable=unused-import
    api as kci_api,
    config as kci_config,
    docker as kci_docker,
    event as kci_event,
    job as kci_job,
    node as kci_node,
    storage as kci_storage,
    user as kci_user,
)


if __name__ == '__main__':
    kci()  # pylint: disable=no-value-for-parameter
