#!/usr/bin/env python3
#
# Copyright (C) 2020 Collabora Limited
# Author: Michal Galka <michal.galka@collabora.com>
# Author: Guillaume Tucker <guillaume.tucker@collabora.com>
#
# This module is free software; you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; either version 2.1 of the License, or (at your option)
# any later version.
#
# This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this library; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

import sys

from kernelci.cli import Args, Command, parse_opts
import kernelci.config.data
import kernelci.data


class cmd_validate(Command):
    help = "Validate the YAML configuration"
    opt_args = [Args.verbose]

    def __call__(self, configs, args):
        # ToDo: Use jsonschema
        return True


class cmd_list_configs(Command):
    help = "List all database configurations"

    def __call__(self, config_data, args):
        db_configs = config_data['db_configs']
        for config_name in db_configs:
            print(config_name)
        return True


class cmd_submit(Command):
    help = "Submit data to the specified database"
    args = [Args.db_config, Args.data_file]
    opt_args = [Args.db_token, Args.verbose]

    def __call__(self, config_data, args):
        config = config_data['db_configs'][args.db_config]
        if args.data_file == '-':
            data = sys.stdin.read()
        else:
            with open(args.data_file, 'r') as f:
                data = f.read()
        db = kernelci.data.get_db(config, args.db_token)
        return db.submit(data, args.verbose)


if __name__ == '__main__':
    opts = parse_opts("kci_data", "config/core/db-configs.yaml", globals())
    configs = kernelci.config.data.from_yaml(opts.yaml_configs)
    status = opts.command(configs, opts)
    sys.exit(0 if status is True else 1)
