labs:

  # ToDo: also run jobs with callbacks sent to BayLibre's KernelCI backend
  lab-baylibre:
    lab_type: lava
    url: 'https://lava.baylibre.com/RPC2/'
    filters:
      - blocklist: {tree: [drm-tip]}
      - passlist:
          plan:
            - baseline
            - baseline-fastboot
            - kselftest
            - preempt-rt

  lab-broonie:
    lab_type: lava
    url: 'https://lava.sirena.org.uk/RPC2/'
    priority: low

  lab-cip:
    lab_type: lava
    url: 'https://lava.ciplatform.org/RPC2'
    filters:
      - blocklist: {tree: [android]}
      - passlist:
          plan:
            - baseline

  lab-clabbe:
    lab_type: lava
    url: 'https://lava.montjoie.ovh/RPC2/'
    filters:
      - passlist:
          plan:
            - baseline
            - baseline-nfs
            - sleep
          tree:
            - kernelci
            - mainline
            - next
            - stable-rc
            - stable

  lab-collabora:
    lab_type: lava
    url: 'https://lava.collabora.co.uk/RPC2/'
    filters:
      - blocklist: {tree: [android]}
      - passlist:
          plan:
            - baseline
            - baseline-nfs
            - cros-ec
            - igt-kms-rockchip
            - igt-kms-exynos
            - igt-kms-tegra
            - igt-gpu-panfrost
            - kselftest
            - ltp
            - sleep
            - usb
            - v4l2-compliance-uvc
            - v4l2-compliance-vivid

  lab-linaro-lkft:
    lab_type: lava
    url: 'https://lkft.validation.linaro.org/RPC2/'
    priority: low
    filters:
      - passlist:
          plan:
            - baseline
            - baseline-uefi
          tree:
            - kernelci
            - next
            - stable-rc
            - stable

  lab-mhart:
    lab_type: lava
    url: 'http://lava.streamtester.net/RPC2/'
    filters:
      - blocklist: {tree: ['android', 'drm-tip', 'linaro-android']}
      - passlist:
          plan:
            - baseline
            - baseline-nfs

  lab-nxp:
    lab_type: lava
    url: 'https://lavalab.nxp.com/RPC2'
    filters:
      - passlist:
          plan:
            - baseline
            - baseline-nfs

  lab-pengutronix:
    lab_type: lava
    url: 'https://hekla.openlab.pengutronix.de/RPC2/'
    filters:
      - passlist:
          plan:
            - baseline

  lab-theobroma-systems:
    lab_type: lava
    url: 'https://lava.theobroma-systems.com/RPC2/'
    filters:
      - passlist:
          plan:
            - baseline
