#!/bin/bash

set -xe

mount_special_fs()
{
    local base="${1:-/root/chromeos}"

    mount udev -t devtmpfs "$base"/dev
    mount proc -t proc "$base"/proc
    mount sysfs -t sysfs "$base"/sys
    mount -t tmpfs tmpfs "$base"/tmp
    mount
}

umount_special_fs()
{
    local base="${1:-/root/chromeos}"

    umount "$base"/dev
    umount "$base"/proc
    umount "$base"/sys
    umount "$base"/tmp
    mount
}

flash_chromeos()
{
    local dev
    local mount_dir=$(basename "$IMAGE_MOUNTPOINT")
    local root_path=$(dirname "$IMAGE_MOUNTPOINT")

    echo "Setting up Chrome OS chroot..."
    mkdir -p "$IMAGE_MOUNTPOINT"
    cd "$root_path"
    dev=$(losetup -P -f --show "$IMAGE_NAME")
    mount "$dev"p3 "$mount_dir" -o ro
    mount_special_fs "$IMAGE_MOUNTPOINT"
    mount --bind . "$mount_dir"/mnt/empty
    ls -l "$mount_dir"/mnt/empty/"$IMAGE_NAME"
    ls -l "$mount_dir"/dev/{mmc*,nvme*} || true

    echo "Starting to flash..."
    chroot "$mount_dir" \
         /usr/sbin/chromeos-install \
        --debug \
        --dst /dev/${FLASH_DEVICE} \
        --payload_image /mnt/empty/"$IMAGE_NAME" \
        --yes
    sync

    umount_special_fs "$IMAGE_MOUNTPOINT"
    umount "$mount_dir"/mnt/empty
    umount "$mount_dir"
    losetup -d "$dev"
}

enable_rw()
{
    local mount_dir=$(basename "$IMAGE_MOUNTPOINT")
    local root_path=$(dirname "$IMAGE_MOUNTPOINT")

    echo "Making the rootfs writeable..."
    mkdir -p "$IMAGE_MOUNTPOINT"
    cd "$root_path"
    mount /dev/${FLASH_DEVICE}p3 "$mount_dir" -o ro
    mount_special_fs "$IMAGE_MOUNTPOINT"
    cd "$mount_dir"
    chroot . \
        /usr/share/vboot/bin/make_dev_ssd.sh \
        --remove_rootfs_verification \
        --force
    cd "$root_path"
    umount_special_fs "$IMAGE_MOUNTPOINT"
    umount "$mount_dir"
    sync
    # Partprobe fails on NVMe chromebooks, ignore it
    partprobe -s /dev/${FLASH_DEVICE} || true
}

fixup_root()
{
    cd /root
    mkdir -p chromeos
    ls -ld chromeos
    mount /dev/${FLASH_DEVICE}p3 chromeos
    ls -ld chromeos
    chown root: chromeos
    ls -ld chromeos
    umount chromeos
    ls -ld chromeos
    mount /dev/${FLASH_DEVICE}p3 chromeos
    ls -ld chromeos
    umount chromeos
    ls -ld chromeos
    sync
}

commands="${*:-flash_chromeos enable_rw fixup_root}"
IMAGE_NAME="${IMAGE_NAME:-octopus-chromiumos-test-image.bin}"
IMAGE_MOUNTPOINT="${IMAGE_MOUNTPOINT:-/root/chromeos}"
FLASH_DEVICE="${FLASH_DEVICE:-mmcblk0}"

if [ "${FLASH_DEVICE}" == "detect" ]; then
    echo "Detecting storage device"
    if [ -e "/dev/mmcblk0" ]; then
       FLASH_DEVICE="mmcblk0"
    elif [ -e "/dev/mmcblk1" ]; then
       FLASH_DEVICE="mmcblk1"
    else
       echo "MMC device not detected!"
       exit 1
    fi
fi

for cmd in $commands; do
    echo "Running [$cmd]"
    $cmd
done

exit 0
