#!/bin/bash
#
# Copyright (C) 2021, 2022 Collabora Limited
# Author: Michal Galka <michal.galka@collabora.com>
# Author: Guillaume Tucker <guillaume.tucker@collabora.com>
#
# This module is free software; you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; either version 2.1 of the License, or (at your option)
# any later version.
#
# This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this library; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

set -xe

MODULES_URL="$1"
BLOCK_DEVICE="${2:-mmcblk0}"
IMAGE_MOUNTPOINT="${3:-/root/chromeos}"

install_modules()
{
    local modules_url="$1"
    local block_device="$2"
    local image_mountpoint="$3"

    local mount_dir=$(basename "$image_mountpoint")
    local root_path=$(dirname "$image_mountpoint")
    local modules_tarball=$(basename "$modules_url")

    echo "Downloading modules from $modules_url..."
    mkdir -p "$image_mountpoint"
    cd "$root_path"
    wget "$modules_url"
    mount PARTUUID=566f7961-6765-7220-746f-20756e697665 "$mount_dir"

    echo "Installing modules..."
    cd "$mount_dir"
    ls -l lib/modules
    rm -rf lib/modules
    tar \
        --no-same-owner \
        --no-same-permissions \
        --no-xattrs \
        --no-selinux \
        --no-acls \
        -xf \
        "$root_path/$modules_tarball"
    ls -l lib/modules
    cd "$root_path"
    umount "$mount_dir"
    sync
}

if [ -z "$MODULES_URL" ]; then
    echo "Missing modules URL"
    echo "Usage: install-modules MODULES_URL BLOCK_DEVICE IMAGE_MOUNTPOINT"
    exit 1
fi

install_modules "$MODULES_URL" "$BLOCK_DEVICE" "$IMAGE_MOUNTPOINT"

exit 0
