# Copyright (C) 2016, 2017 Linaro Limited
# Author: Matt Hart <matthew.hart@linaro.org>
# Author: Tyler Baker <tyler.baker@linaro.org>
#
# Copyright (C) 2016, 2017 Baylibre SAS
# Author: Jerome Brunet <jbrunet@baylibre.com>
# Author: Kevin Hilman <khilman@baylibre.com>
#
# Copyright (C) 2016, 2017 Free Electrons
# Author: Alexandre Belloni <alexandre.belloni@free-electrons.com>
# Author: Florent Jacquet <florent.jacquet@free-electrons.com>
# Author: Quentin Schulz <quentin.schulz@free-electrons.com>
#
# Copyright (C) 2016, 2017 Pengutronix
# Author: Michael Grzeschik <m.grzeschik@pengutronix.de>
#
# Copyright (C) 2017, 2018 Collabora Limited
# Author: Tomeu Vizoso <tomeu.vizoso@collabora.com>
# Author: Guillaume Tucker <guillaume.tucker@collabora.com>
#
# This module is free software; you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; either version 2.1 of the License, or (at your option)
# any later version.
#
# This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this library; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

alpine_db = {'device_type': 'alpine-db',
                      'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                      'kernel_defconfig_blacklist': [],
                      'defconfig_blacklist': ['allmodconfig'],
                      'kernel_blacklist': [],
                      'nfs_blacklist': [],
                      'lpae': False,
                      'fastboot': False,
                      'mach': 'alpine'}

bcm2836_rpi_2_b = {'device_type': 'bcm2836-rpi-2-b',
                      'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                                    'generic-uboot-tftp-ramdisk-sleep-template.jinja2',
                                    'generic-uboot-tftp-ramdisk-usb-template.jinja2'],
                      'kernel_defconfig_blacklist': [],
                      'defconfig_blacklist': ['allmodconfig'],
                      'kernel_blacklist': [],
                      'nfs_blacklist': [],
                      'lpae': False,
                      'fastboot': False,
                      'mach': 'bcm'}

bcm2837_rpi_3_b = {'device_type': 'bcm2837-rpi-3-b',
               'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                             'generic-uboot-tftp-ramdisk-kselftest-template.jinja2',
                             'generic-uboot-tftp-ramdisk-simple-template.jinja2',
                             'generic-uboot-tftp-ramdisk-usb-template.jinja2'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['allnoconfig',
                                       'allmodconfig'],
               'arch_blacklist': ['arm'],
               'kernel_blacklist': ['v4.13-', 'v4.13.', 'v4.14-rc1', 'v4.14-rc5', 'for-4.15', 'v3.', '4.4-', '4.9-'],
               'nfs_blacklist': [],
               'lpae': False,
               'fastboot': False,
               'context': {'console_device': 'ttyS1', 'test_character_delay': 10},
               'mach': 'bcm'}

bcm2837_rpi_3_b_32 = {'device_type': 'bcm2837-rpi-3-b-32',
               'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                             'generic-uboot-tftp-ramdisk-kselftest-template.jinja2',
                             'generic-uboot-tftp-ramdisk-simple-template.jinja2'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['allnoconfig',
                                       'allmodconfig'],
               'defconfig_whitelist': ['bcm2835_defconfig'],
               'arch_blacklist': ['arm64'],
               'kernel_blacklist': ['v4.13-', 'v4.13.', 'v4.14-rc1', 'v4.14-rc5', 'for-4.15', 'v3.', '4.4-', '4.9-'],
               'nfs_blacklist': [],
               'lpae': False,
               'fastboot': False,
               'context': {'console_device': 'ttyS1', 'test_character_delay': 10},
               'mach': 'bcm'}

armada_370_db = {'device_type': 'armada-370-db',
                       'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['allmodconfig'],
                       'kernel_blacklist': ['v3'],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False,
                       'mach': 'mvebu'}

orion5x_rd88f5182_nas = {'device_type': 'orion5x-rd88f5182-nas',
                       'templates': ['generic-uboot-tftp-nfs-template.jinja2'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False,
                       'mach': 'mvebu'}

armada_370_rd = {'device_type': 'armada-370-rd',
                       'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
		       'kernel_defconfig_blacklist': [{'kernel_version': 'v4.0', 'defconfig': 'multi_v7_defconfig'},
						      {'kernel_version': 'v4.1', 'defconfig': 'multi_v7_defconfig'},
						      {'kernel_version': 'v4.2', 'defconfig': 'multi_v7_defconfig'},
						      {'kernel_version': 'v4.3', 'defconfig': 'multi_v7_defconfig'}],
                       'defconfig_blacklist': ['allmodconfig'],
                       'kernel_blacklist': ['v3'],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False,
                       'mach': 'mvebu'}

armada_375_db = {'device_type': 'armada-375-db',
                       'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False,
                       'mach': 'mvebu'}

armada_385_db_ap = {'device_type': 'armada-385-db-ap',
                       'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False,
                       'mach': 'mvebu'}

armada_388_gp = {'device_type': 'armada-388-gp',
                       'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False,
                       'mach': 'mvebu'}

armada_398_db = {'device_type': 'armada-398-db',
                       'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False,
                       'mach': 'mvebu'}

kirkwood_db_88f6282 = {'device_type': 'kirkwood-db-88f6282',
                       'templates': ['generic-uboot-tftp-nfs-template.jinja2'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['allmodconfig',
			# To be removed once NFS is working for this defconfig
					       'multi_v5_defconfig'],
                       'kernel_blacklist': ['v3'],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False,
                       'mach': 'mvebu'}

armada_3720_db = {'device_type': 'armada-3720-db',
                       'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False,
                       'mach': 'mvebu'}

armada_7040_db = {'device_type': 'armada-7040-db',
                       'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['allmodconfig'],
                       'kernel_blacklist': ['v4.6'],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False,
                       'mach': 'mvebu'}

armada_8040_db = {'device_type': 'armada-8040-db',
                       'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False,
                       'mach': 'mvebu'}

armada_xp_db = {'device_type': 'armada-xp-db',
                       'templates': ['generic-uboot-tftp-nfs-template.jinja2'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False,
                       'mach': 'mvebu'}

armada_xp_gp = {'device_type': 'armada-xp-gp',
                       'templates': ['generic-uboot-tftp-nfs-template.jinja2'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False,
                       'mach': 'mvebu'}

arndale = {'device_type': 'arndale',
           'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                         'generic-uboot-tftp-ramdisk-kselftest-template.jinja2'],
           'kernel_defconfig_blacklist': [],
           'defconfig_blacklist': ['allmodconfig',
                                   'multi_v7_defconfig+CONFIG_SMP=n'],
           'kernel_blacklist': [],
           'nfs_blacklist': [],
           'lpae': True,
           'fastboot': False,
           'mach': 'exynos'}

snow = {'device_type': 'snow',
        'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                      'generic-uboot-tftp-ramdisk-kselftest-template.jinja2',
                      'generic-uboot-tftp-nfs-template.jinja2'],
        'kernel_defconfig_blacklist': [],
        'defconfig_blacklist': ['allmodconfig',
                                'multi_v7_defconfig+CONFIG_SMP=n'],
        'kernel_blacklist': [],
        'nfs_blacklist': [],
        'lpae': True,
        'fastboot': False,
        'mach': 'exynos'}

arndale_octa = {'device_type': 'arndale-octa',
                'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                              'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                              'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                              'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                'kernel_defconfig_blacklist': [],
                'defconfig_blacklist': ['allmodconfig',
                                        'multi_v7_defconfig+linaro-base+distribution'],
                'kernel_blacklist': [],
                'nfs_blacklist': ['v3.',
                                  'lsk-v3.'],
                'lpae': True,
                'fastboot': False,
                'mach': 'exynos'}

peach_pi = {'device_type': 'peach-pi',
            'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                          'generic-uboot-tftp-ramdisk-kselftest-template.jinja2',
                          'generic-uboot-tftp-ramdisk-sleep-template.jinja2',
                          'generic-uboot-tftp-ramdisk-usb-template.jinja2',
                          'generic-uboot-tftp-ramdisk-cros-ec-template.jinja2'],
            'kernel_defconfig_blacklist': [],
            'defconfig_blacklist': ['allmodconfig'],
            'kernel_blacklist': [],
            'nfs_blacklist': ['v3.',
                              'lsk-v3.'],
            'lpae': True,
            'fastboot': False,
            'mach': 'exynos'}

odroid_xu3 = {'device_type': 'odroid-xu3',
              'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                            'generic-uboot-tftp-ramdisk-kselftest-template.jinja2',
                            'generic-uboot-tftp-nfs-template.jinja2',
                            'generic-uboot-tftp-ramdisk-sleep-template.jinja2',
                            'generic-uboot-tftp-ramdisk-usb-template.jinja2',
                            'generic-uboot-tftp-ramdisk-igt-template.jinja2'],
              'kernel_defconfig_blacklist': [],
              'defconfig_blacklist': ['allmodconfig'],
              'kernel_blacklist': [],
              'nfs_blacklist': [],
              'lpae': True,
              'fastboot': False,
              'mach': 'exynos'}

odroid_x2 = {'device_type': 'odroid-x2',
             'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                           'generic-uboot-tftp-ramdisk-kselftest-template.jinja2',
                           'generic-uboot-tftp-nfs-template.jinja2'],
             'kernel_defconfig_blacklist': [],
             'defconfig_blacklist': ['allmodconfig'],
             'kernel_blacklist': [],
             'nfs_blacklist': [],
             'lpae': False,
             'fastboot': False,
             'mach': 'exynos'}

beaglebone_black = {'device_type': 'beaglebone-black',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                                  'generic-uboot-tftp-nfs-template.jinja2',
                                  'generic-uboot-tftp-ramdisk-kselftest-template.jinja2',
                                  'generic-uboot-tftp-ramdisk-simple-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lab_blacklist': ['lab-baylibre'],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'omap2'}

beagle_xm = {'device_type': 'beagle-xm',
             'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                           'generic-uboot-tftp-ramdisk-kselftest-template.jinja2'],
             'kernel_defconfig_blacklist': [],
             'defconfig_blacklist': ['allmodconfig'],
             'kernel_blacklist': ['v3.14',
                                  'lsk-v3.14'],
             'nfs_blacklist': [],
             'lpae': False,
             'fastboot': False,
             'mach': 'omap2'}

panda_es = {'device_type': 'panda-es',
            'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                          'generic-uboot-tftp-ramdisk-kselftest-template.jinja2'],
            'kernel_defconfig_blacklist': [],
            'defconfig_blacklist': ['allmodconfig'],
            'kernel_blacklist': [],
            'nfs_blacklist': [],
            'lpae': False,
            'fastboot': False,
            'mach': 'omap2'}

panda = {'device_type': 'panda',
         'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                       'generic-uboot-tftp-ramdisk-kselftest-template.jinja2'],
         'kernel_defconfig_blacklist': [],
         'defconfig_blacklist': ['allmodconfig',
                                 'multi_v7_defconfig+CONFIG_PROVE_LOCKING=y',
                                 'multi_v7_defconfig+kselftest'],
         'kernel_blacklist': [],
         'nfs_blacklist': [],
         'lpae': False,
         'fastboot': False,
         'mach': 'omap2'}

dra7_evm = {'device_type': 'dra7-evm',
            'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                          'generic-uboot-tftp-ramdisk-kselftest-template.jinja2',
                          'generic-uboot-tftp-ramdisk-simple-template.jinja2'],
            'kernel_defconfig_blacklist': [],
            'defconfig_blacklist': ['allmodconfig'],
            'kernel_blacklist': [],
            'nfs_blacklist': [],
            'lpae': False,
            'fastboot': False,
            'mach': 'omap2'}

d03 = {'device_type': 'd03',
       'templates': ['generic-grub-tftp-ramdisk-template.jinja2'],
       'kernel_defconfig_blacklist': [],
        'defconfig_blacklist': ['allnoconfig',
                                'allmodconfig'],
       'kernel_blacklist': [],
       'nfs_blacklist': [],
       'lpae': True,
       'fastboot': False,
       'mach': 'hisi'}

d05 = {'device_type': 'hip07-d05',
       'templates': ['generic-grub-tftp-ramdisk-template.jinja2',
                     'generic-grub-tftp-nfs-template.jinja2'],
       'kernel_defconfig_blacklist': [],
       'defconfig_blacklist': ['allnoconfig',
                               'allmodconfig'],
       'kernel_blacklist': [],
       'nfs_blacklist': [],
       'lpae': True,
       'fastboot': False,
       'mach': 'hisi'}

imx6ul_pico_hobbit = {'device_type': 'imx6ul-pico-hobbit',
                   'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                 'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                                 'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                                 'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                                 'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                                 'generic-arm-dtb-kernel-ci-kselftest-template.json',
                                 'generic-arm-dtb-kernel-ci-hackbench-template.json'],
                   'kernel_defconfig_blacklist': [],
                   'defconfig_blacklist': ['imx_v4_v5_defconfig',
                                           'multi_v5_defconfig',
                                           'allmodconfig'],
                   'kernel_blacklist': [],
                   'nfs_blacklist': [],
                   'lpae': False,
                   'fastboot': False,
                   'mach': 'imx'}

imx6q_sabrelite = {'device_type': 'imx6q-sabrelite',
                   'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                                 'generic-uboot-tftp-ramdisk-kselftest-template.jinja2',
                                 'generic-uboot-tftp-nfs-template.jinja2',
                                 'generic-uboot-tftp-ramdisk-sleep-template.jinja2',
                                 'generic-uboot-tftp-ramdisk-usb-template.jinja2'],
                   'kernel_defconfig_blacklist': [],
                   'defconfig_blacklist': ['imx_v4_v5_defconfig',
                                           'imx_v6_v7_defconfig',
                                           'multi_v5_defconfig',
                                           'allmodconfig',
                                           'multi_v7_defconfig+kselftest'],
                   'kernel_blacklist': ['v3.18',
                                        'lsk-v3.18'],
                   'nfs_blacklist': [],
                   'lpae': False,
                   'fastboot': False,
                   'mach': 'imx'}

meson8b_odroidc1 = {'device_type': 'meson8b-odroidc1',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                                  'generic-uboot-tftp-ramdisk-kselftest-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'meson'}

meson_gxbb_odroidc2 = {'device_type': 'meson-gxbb-odroidc2',
               'templates': ['generic-arm64-dtb-kernel-ci-boot-template.json',
                             'generic-arm64-dtb-kernel-ci-boot-be-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-cyclictest-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-hackbench-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-lmbench-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-ltp-realtime-template.json',
                             'generic-arm64-dtb-kernel-ci-kselftest-template.json'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['allnoconfig',
                                       'allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': [],
               'lpae': False,
               'fastboot': True,
               'mach': 'amlogic',
               'boot_be': True}

meson_gxbb_nanopi_k2 = {'device_type': 'meson-gxbb-nanopi-k2',
               'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                             'generic-uboot-tftp-ramdisk-kselftest-template.jinja2',
                             'generic-uboot-tftp-ramdisk-boot-be-template.jinja2',
                             'generic-uboot-tftp-ramdisk-simple-template.jinja2'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['allnoconfig',
                                       'allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': [],
               'lpae': False,
               'fastboot': False,
               'mach': 'amlogic',
               'boot_be': True}

meson_gxbb_p200 = {'device_type': 'meson-gxbb-p200',
               'templates': ['generic-arm64-dtb-kernel-ci-boot-template.json',
                             'generic-arm64-dtb-kernel-ci-boot-be-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-cyclictest-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-hackbench-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-lmbench-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-ltp-realtime-template.json',
                             'generic-arm64-dtb-kernel-ci-kselftest-template.json'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['allnoconfig',
                                       'allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': [],
               'lpae': False,
               'fastboot': True,
               'mach': 'amlogic',
               'boot_be': True}

meson_gxl_s905x_khadas_vim  = {'device_type': 'meson-gxl-s905x-khadas-vim',
               'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                             'generic-uboot-tftp-ramdisk-kselftest-template.jinja2',
                             'generic-uboot-tftp-ramdisk-boot-be-template.jinja2',
                             'generic-uboot-tftp-ramdisk-simple-template.jinja2'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['allnoconfig',
                                       'allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': [],
               'lpae': False,
               'fastboot': False,
               'mach': 'amlogic',
               'boot_be': True}

meson_gxl_s905x_libretech_cc  = {'device_type': 'meson-gxl-s905x-libretech-cc',
               'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                             'generic-uboot-tftp-ramdisk-kselftest-template.jinja2',
                             'generic-uboot-tftp-ramdisk-boot-be-template.jinja2',
                             'generic-uboot-tftp-ramdisk-simple-template.jinja2'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['allnoconfig',
                                       'allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': [],
               'lpae': False,
               'fastboot': False,
               'mach': 'amlogic',
               'boot_be': True}

r8a7795_salvator_x = {'device_type': 'r8a7795-salvator-x',
               'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                             'generic-uboot-tftp-ramdisk-boot-be-template.jinja2',
                             'generic-uboot-tftp-nfs-template.jinja2'
                             'generic-uboot-tftp-ramdisk-kselftest-template.jinja2',
                             'generic-uboot-tftp-ramdisk-simple-template.jinja2'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['allnoconfig',
                                       'allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': [],
               'lpae': False,
               'fastboot': False,
               'mach': 'renesas',
               'boot_be': True}

r8a7796_m3ulcb = {'device_type': 'r8a7796-m3ulcb',
               'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                             'generic-uboot-tftp-ramdisk-simple-template.jinja2',
                             'generic-uboot-tftp-ramdisk-usb-template.jinja2'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['allnoconfig',
                                       'allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': [],
               'lpae': False,
               'fastboot': False,
               'mach': 'renesas'}

r8a7791_porter = {'device_type': 'r8a7791-porter',
               'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': [],
               'lpae': False,
               'fastboot': False,
               'mach': 'renesas'}


da850_lcdk = {'device_type': 'da850-lcdk',
                    'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                  'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                                  'generic-arm-dtb-kernel-ci-kselftest-template.json',
                                  'generic-arm-dtb-kernel-ci-hackbench-template.json'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'davinci'}

ifc6410 = {'device_type': 'ifc6410',
           'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                         'generic-arm-dtb-kernel-ci-kselftest-template.json',
                         'generic-arm-dtb-kernel-ci-hackbench-template.json'],
           'kernel_defconfig_blacklist': [],
           'defconfig_blacklist': ['allmodconfig'],
           'kernel_blacklist': [],
           'nfs_blacklist': [],
           'lpae': False,
           'fastboot': True,
           'mach': 'qcom'}

jetson_tk1 = {'device_type': 'jetson-tk1',
              'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                            'generic-uboot-tftp-nfs-template.jinja2',
                            'generic-uboot-tftp-ramdisk-kselftest-template.jinja2'],
              'kernel_defconfig_blacklist': [],
              'defconfig_blacklist': ['allmodconfig',
                                      'multi_v7_defconfig+kselftest'],
              'kernel_blacklist': [],
              'nfs_blacklist': [],
              'lpae': True,
              'fastboot': False,
              'mach': 'tegra'}

tegra124_nyan_big = {'device_type': 'tegra124-nyan-big',
                     'templates': ['generic-depthcharge-tftp-ramdisk-template.jinja2',
                                   'generic-depthcharge-tftp-ramdisk-sleep-template.jinja2',
                                   'generic-depthcharge-tftp-ramdisk-usb-template.jinja2',
                                   'generic-depthcharge-tftp-ramdisk-igt-template.jinja2',
                                   'generic-depthcharge-tftp-ramdisk-cros-ec-template.jinja2'],
                     'kernel_defconfig_blacklist': [],
                     'defconfig_blacklist': ['allmodconfig'],
                     'kernel_blacklist': [],
                     'nfs_blacklist': [],
                     'lpae': True,
                     'fastboot': False,
                     'mach': 'tegra'}

zynq_zc702 = {'device_type': 'zynq-zc702',
              'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
              'kernel_defconfig_blacklist': [],
              'defconfig_blacklist': ['allmodconfig',
                                      'multi_v7_defconfig+linaro-base+distribution'],
              'kernel_blacklist': [],
              'nfs_blacklist': [],
              'lpae': False,
              'fastboot': False,
              'mach': 'zynq'}

rk3288_rock2_square = {'device_type': 'rk3288-rock2-square',
                       'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                                     'generic-uboot-tftp-ramdisk-kselftest-template.jinja2',
                                     'generic-uboot-tftp-nfs-template.jinja2',
                                     'generic-uboot-tftp-ramdisk-sleep-template.jinja2',
                                     'generic-uboot-tftp-ramdisk-usb-template.jinja2'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': True,
                       'fastboot': True,
                       'mach': 'rockchip'}

rk3288_veyron_jaq = {'device_type': 'rk3288-veyron-jaq',
                     'templates': ['generic-depthcharge-tftp-ramdisk-template.jinja2',
                                   'generic-depthcharge-tftp-nfs-template.jinja2',
                                   'generic-depthcharge-tftp-ramdisk-sleep-template.jinja2',
                                   'generic-depthcharge-tftp-ramdisk-usb-template.jinja2',
                                   'generic-depthcharge-tftp-ramdisk-v4l2-template.jinja2',
                                   'generic-depthcharge-tftp-ramdisk-igt-template.jinja2',
                                   'generic-depthcharge-tftp-ramdisk-cros-ec-template.jinja2'],
                     'kernel_defconfig_blacklist': [],
                     'defconfig_blacklist': ['allmodconfig'],
                     'kernel_blacklist': [],
                     'nfs_blacklist': [],
                     'lpae': True,
                     'fastboot': False,
                     'mach': 'rockchip'}

rk3399_gru_kevin = {'device_type': 'rk3399-gru-kevin',
                    'templates': ['generic-depthcharge-tftp-ramdisk-template.jinja2',
                                  'generic-depthcharge-tftp-nfs-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': True,
                    'fastboot': False,
                    'mach': 'rockchip'}

rk3399_puma_haikou = {'device_type': 'rk3399-puma-haikou',
               'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                             'generic-uboot-tftp-ramdisk-kselftest-template.jinja2'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['allmodconfig'],
               'arch_blacklist': ['arm'],
               'kernel_blacklist': ['v3.', 'v4.1.', 'v4.2.', 'v4.3.', 'v4.4.', 'v4.5.', '4.6.', '4.7.',
                                    'v4.8.', 'v4.9.', 'v4.10.', 'v4.11.', 'v4.12.', 'v4.13.'],
               'nfs_blacklist': [],
               'lpae': False,
               'fastboot': False,
               'mach': 'rockchip'}

qemu = {'device_type': 'qemu',
        'templates': ['qemu-generic-boot-template.jinja2'],
        'kernel_defconfig_blacklist': [],
        'defconfig_whitelist': ['defconfig',
                                'x86_64_defconfig',
                                'vexpress_defconfig',
                                'multi_v7_defconfig'],
        'defconfig_blacklist': [],
        'kernel_blacklist': [],
        'nfs_blacklist': [],
        'lpae': False,
        'fastboot': False,
        'mach': 'qemu'}

apq8016_sbc = {'device_type': 'apq8016-sbc',
               'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                             'generic-uboot-tftp-ramdisk-kselftest-template.jinja2'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['allnoconfig',
                                       'allmodconfig',
                                       'defconfig+CONFIG_KASAN=y'],
               'kernel_blacklist': [],
               'nfs_blacklist': [],
               'lpae': False,
               'fastboot': True,
               'mach': 'qcom'}

apm_mustang = {'device_type': 'mustang',
               'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                             'generic-uboot-tftp-ramdisk-kselftest-template.jinja2',
                             'generic-uboot-tftp-nfs-template.jinja2'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['allnoconfig',
                                       'allmodconfig',
                                       'defconfig+CONFIG_RANDOMIZE_BASE=y'],
               'kernel_blacklist': [],
               'nfs_blacklist': ['v3.10',
                                 'lsk-v3.10',
                                 'v3.12',
                                 'v3.14',
                                 'lsk-v3.14',
                                 'v3.18'],
               'be_blacklist': ['v3.10'],
               'lpae': False,
               'fastboot': False,
               'mach': 'apm'}

x86_pentium4 = {'device_type': 'x86-pentium4',
       'templates': ['generic-grub-tftp-ramdisk-template.jinja2',
                     'generic-grub-tftp-ramdisk-kselftest-template.jinja2',
                     'generic-grub-tftp-nfs-template.jinja2'],
       'kernel_defconfig_blacklist': [],
       'defconfig_blacklist': ['x86_64_defconfig',
                               'allnoconfig',
                               'allmodconfig',
                               'allmodconfig+CONFIG_OF=n',
                               'tinyconfig',
                               'kvm_guest.config'],
       'kernel_blacklist': [],
       'nfs_blacklist': [],
       'lpae': False,
       'fastboot': False,
       'mach': 'x86'}

x86_celeron = {'device_type': 'x86-celeron',
       'templates': ['generic-ipxe-tftp-ramdisk-template.jinja2',
                     'generic-ipxe-tftp-nfs-template.jinja2',
                     'generic-ipxe-tftp-ramdisk-simple-template.jinja2'],
       'kernel_defconfig_blacklist': [],
       'defconfig_blacklist': ['x86_64_defconfig',
                               'allnoconfig',
                               'allmodconfig',
                               'allmodconfig+CONFIG_OF=n',
                               'tinyconfig',
                               'kvm_guest.config'],
       'kernel_blacklist': [],
       'nfs_blacklist': [],
       'lpae': False,
       'fastboot': False,
       'mach': 'x86'}

x86_x5_z8350 = {'device_type': 'x86-x5-z8350',
       'templates': ['generic-grub-tftp-ramdisk-template.jinja2',
                     'generic-grub-tftp-nfs-template.jinja2'],
       'kernel_defconfig_blacklist': [],
       'defconfig_blacklist': ['i386_defconfig',
                               'allnoconfig',
                               'allmodconfig',
                               'allmodconfig+CONFIG_OF=n',
                               'tinyconfig',
                               'kvm_guest.config'],
       'kernel_blacklist': [],
       'nfs_blacklist': [],
       'lpae': False,
       'fastboot': False,
       'mach': 'x86'}

x86_atom330 = {'device_type': 'x86-atom330',
                         'templates': ['generic-ipxe-tftp-ramdisk-template.jinja2',
                                       'generic-ipxe-tftp-ramdisk-kselftest-template.jinja2',
                                       'generic-ipxe-tftp-nfs-template.jinja2',
                                       'generic-ipxe-tftp-ramdisk-simple-template.jinja2'],
                         'kernel_defconfig_blacklist': [],
                         'defconfig_blacklist': ['i386_defconfig',
                                                 'allnoconfig',
                                                 'allmodconfig',
                                                 'allmodconfig+CONFIG_OF=n',
                                                 'tinyconfig',
                                                 'kvm_guest.config'],
                         'kernel_blacklist': [],
                         'nfs_blacklist': [],
                         'lpae': False,
                         'fastboot': False,
                         'mach': 'x86'}

minnowboard_max_E3825 = {'device_type': 'minnowboard-max-E3825',
                         'templates': ['generic-x86-kernel-ci-boot-template.json',
                                       'generic-x86-kernel-ci-cyclictest-template.json',
                                       'generic-x86-kernel-ci-kselftest-template.json',
                                       'generic-x86-kernel-ci-hackbench-template.json',
                                       'generic-x86-kernel-ci-lmbench-template.json',
                                       'generic-x86-kernel-ci-ltp-realtime-template.json'],
                         'kernel_defconfig_blacklist': [],
                         'defconfig_blacklist': ['i386_defconfig',
                                                 'allnoconfig',
                                                 'allmodconfig',
                                                 'allmodconfig+CONFIG_OF=n',
                                                 'tinyconfig',
                                                 'kvm_guest.config'],
                         'kernel_blacklist': [],
                         'nfs_blacklist': [],
                         'lpae': False,
                         'fastboot': False,
                         'mach': 'x86'}

imx6dl_riotboard = {'device_type': 'imx6dl-riotboard',
                    'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                  'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                                  'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                                  'generic-arm-dtb-kernel-ci-kselftest-template.json',
                                  'generic-arm-dtb-kernel-ci-hackbench-template.json'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['imx_v4_v5_defconfig',
                                            'multi_v5_defconfig',
                                            'allmodconfig',
                                            'multi_v7_defconfig+CONFIG_EFI=y'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'imx'}

imx53_qsbr = {'device_type': 'imx53-qsbr',
              'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                            'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                            'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                            'generic-arm-dtb-kernel-ci-kselftest-template.json',
                            'generic-arm-dtb-kernel-ci-hackbench-template.json'],
              'kernel_defconfig_blacklist': [],
              'defconfig_blacklist': ['imx_v4_v5_defconfig',
                                      'multi_v5_defconfig',
                                      'allmodconfig',
                                      'multi_v7_defconfig+CONFIG_EFI=y'],
              'kernel_blacklist': [],
              'nfs_blacklist': [],
              'lpae': False,
              'fastboot': False,
              'mach': 'imx'}

imx28_duckbill = {'device_type': 'imx28-duckbill',
                  'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                  'kernel_defconfig_blacklist': [],
                  'defconfig_blacklist': ['allmodconfig'],
                  'kernel_blacklist': ['v3.',
                                       'v4.0',
                                       'v4.1',
                                       'v4.2',
                                       'v4.3',
                                       'v4.4',
                                       'v4.5'],
                  'nfs_blacklist': [],
                  'lpae': False,
                  'fastboot': False,
                  'mach': 'imx'}

imx23_olinuxino = {'device_type': 'imx23-olinuxino',
                   'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                   'kernel_defconfig_blacklist': [],
                   'defconfig_blacklist': ['allmodconfig'],
                   'kernel_blacklist': ['v3.',
                                        'v4.0',
                                        'v4.1',
                                        'v4.2',
                                        'v4.3',
                                        'v4.4',
                                        'v4.5'],
                   'nfs_blacklist': [],
                   'lpae': False,
                   'fastboot': False,
                   'mach': 'imx'}

socfpga_cyclone5_socrates = {'device_type': 'socfpga-cyclone5-socrates',
                             'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                           'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                                           'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                                           'generic-arm-dtb-kernel-ci-kselftest-template.json',
                                           'generic-arm-dtb-kernel-ci-hackbench-template.json'],
                             'kernel_defconfig_blacklist': [{'kernel_version': 'v4.5', 'defconfig': 'socfpga_defconfig'},
                                                            {'kernel_version': 'v4.4', 'defconfig': 'socfpga_defconfig'},
                                                            {'kernel_version': 'v4.3', 'defconfig': 'socfpga_defconfig'},
                                                            {'kernel_version': 'v4.2', 'defconfig': 'socfpga_defconfig'},
                                                            {'kernel_version': 'v4.1', 'defconfig': 'socfpga_defconfig'},
                                                            {'kernel_version': 'v4.0', 'defconfig': 'socfpga_defconfig'},
                                                            {'kernel_version': 'v3.', 'defconfig': 'socfpga_defconfig'}],
                             'defconfig_blacklist': ['allmodconfig',
                                                     'multi_v7_defconfig+CONFIG_EFI=y'],
                             'kernel_blacklist': [],
                             'nfs_blacklist': [],
                             'lpae': False,
                             'fastboot': False,
                             'mach': 'socfpga'}

imx27_phycard_s = {'device_type': 'imx27-phytec-phycard-s-rdk',
                   'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                   'kernel_defconfig_blacklist': [],
                   'defconfig_blacklist': ['allmodconfig'],
                   'kernel_blacklist': ['v3.',
                                        'v4.0',
                                        'v4.1',
                                        'v4.2',
                                        'v4.3',
                                        'v4.4',
                                        'v4.5',
                                        'v4.6'],
                   'nfs_blacklist': [],
                   'lpae': False,
                   'fastboot': False,
                   'mach': 'imx'}

openblocks_ax3 = {'device_type': 'armada-xp-openblocks-ax3-4',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig',
                                            'multi_v7_defconfig+CONFIG_SMP=n'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'mvebu'}

openblocks_a7 = {'device_type': 'kirkwood-openblocks_a7',
                 'templates': ['generic-uboot-tftp-nfs-template.jinja2'],
                 'kernel_defconfig_blacklist': [],
                 'defconfig_blacklist': ['allmodconfig',
		 # To be removed once NFS is working for this defconfig
					 'multi_v5_defconfig'],
                 'kernel_blacklist': ['v3'],
                 'nfs_blacklist': [],
                 'lpae': False,
                 'fastboot': False,
                 'mach': 'mvebu'}

armada_xp_linksys_mamba = {'device_type': 'armada-xp-linksys-mamba',
			   'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
			   'kernel_defconfig_blacklist': [],
			   'defconfig_blacklist': ['allmodconfig',
						   'multi_v7_defconfig+CONFIG_SMP=n'],
			   'kernel_blacklist': [],
			   'nfs_blacklist': [],
			   'lpae': False,
			   'fastboot': False,
               'mach': 'mvebu'}

armada_388_clearfog = {'device_type': 'armada-388-clearfog',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig',
                                            'multi_v7_defconfig+CONFIG_SMP=n'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'mvebu'}

chip_pro = {'device_type': 'sun5i-gr8-chip-pro',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig',
                                            'multi_v7_defconfig+CONFIG_LKDTM=y'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'allwinner'}

chip = {'device_type': 'sun5i-r8-chip',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'allwinner'}

imx6q_nitrogen6x = {'device_type': 'imx6q-nitrogen6x',
                   'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                   'kernel_defconfig_blacklist': [],
                   'defconfig_blacklist': ['allmodconfig',
					   'imx_v4_v5_defconfig',
					   'multi_v5_defconfig'],
                   'kernel_blacklist': [],
                   'nfs_blacklist': [],
                   'lpae': False,
                   'fastboot': False,
                   'mach': 'imx'}

at91sam9m10g45ek = {'device_type': 'at91sam9m10g45ek',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig',
					    'multi_v7_defconfig',
					    'at91rm9200_defconfig',
					    'at91sam9261_9g10_defconfig',
					    'at91sam9263_defconfig',
					    'at91sam9rl_defconfig',
					    'at91x40_defconfig',
					    'sama5_defconfig',
					    'at91sam9260_9g20_defconfig',
					    'at91sam9260_defconfig',
					    'at91sam9261_defconfig',
					    'at91sam9g20_defconfig',
					    'at91sam9rl_defconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'at91'}

sam9261ek = {'device_type': 'at91sam9261ek',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig',
					    'multi_v7_defconfig',
					    'at91rm9200_defconfig',
					    'at91sam9263_defconfig',
					    'at91sam9g45_defconfig',
					    'at91sam9rl_defconfig',
					    'at91x40_defconfig',
					    'sama5_defconfig',
					    'at91sam9260_9g20_defconfig',
					    'at91sam9260_defconfig',
					    'at91sam9g20_defconfig',
					    'at91sam9rl_defconfig'],
                    'kernel_blacklist': ['v3.'],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'at91'}

sam9x25ek = {'device_type': 'at91sam9x25ek',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig',
					    'multi_v7_defconfig',
					    'at91rm9200_defconfig',
					    'at91sam9261_9g10_defconfig',
					    'at91sam9263_defconfig',
					    'at91sam9g45_defconfig',
					    'at91sam9rl_defconfig',
					    'at91x40_defconfig',
					    'sama5_defconfig',
					    'at91sam9260_9g20_defconfig',
					    'at91sam9260_defconfig',
					    'at91sam9261_defconfig',
					    'at91sam9g20_defconfig',
					    'at91sam9rl_defconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'at91'}

at91sam9x35ek = {'device_type': 'at91sam9x35ek',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig',
					    'multi_v7_defconfig',
					    'at91rm9200_defconfig',
					    'at91sam9261_9g10_defconfig',
					    'at91sam9263_defconfig',
					    'at91sam9g45_defconfig',
					    'at91sam9rl_defconfig',
					    'at91x40_defconfig',
					    'sama5_defconfig',
					    'at91sam9260_9g20_defconfig',
					    'at91sam9260_defconfig',
					    'at91sam9261_defconfig',
					    'at91sam9g20_defconfig',
					    'at91sam9rl_defconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'at91'}

at91rm9200ek = {'device_type': 'at91rm9200ek',
                    'templates': ['generic-uboot-tftp-nfs-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig'],
                    'kernel_blacklist': ['v3'],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'at91'}

at91_sama5d2_xplained = {'device_type': 'at91-sama5d2_xplained',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'at91'}

at91_sama5d4_xplained = {'device_type': 'at91-sama5d4_xplained',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'at91'}

sun50i_h5_libretech_all_h3_cc = {'device_type': 'sun50i-h5-libretech-all-h3-cc',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'allwinner'}

sun8i_a23_evb = {'device_type': 'sun8i-a23-evb',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'allwinner'}

sun8i_a83t_allwinner_h8homlet_v2 = {'device_type': 'sun8i-a83t-allwinner-h8homlet-v2',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'allwinner'}

sun8i_h2_plus_libretech_all_h3_cc = {'device_type': 'sun8i-h2-plus-libretech-all-h3-cc',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'allwinner'}

sun8i_h3_libretech_all_h3_cc = {'device_type': 'sun8i-h3-libretech-all-h3-cc',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'allwinner'}

sun8i_h3_orangepi_pc = {'device_type': 'sun8i-h3-orangepi-pc',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'allwinner'}

sinlinx_sina33 = {'device_type': 'sun8i-a33-sinlinx-sina33',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'allwinner'}

dove_cubox = {'device_type': 'dove-cubox',
                       'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False,
                       'mach': 'mvebu'}

synquacer_acpi = {'device_type': 'synquacer-acpi',
       'templates': ['generic-grub-tftp-ramdisk-template.jinja2'],
       'kernel_defconfig_blacklist': [],
       'defconfig_blacklist': ['allmodconfig'],
       'kernel_blacklist': ['v3.', 'v4.4.'],
       'nfs_blacklist': [],
       'lpae': False,
       'fastboot': False,
       'defconfig_whitelist': ['defconfig'],
       'mach': 'socionext'}

synquacer_dtb = {'device_type': 'synquacer-dtb',
       'templates': ['generic-grub-tftp-ramdisk-template.jinja2'],
       'kernel_defconfig_blacklist': [],
       'defconfig_blacklist': ['allmodconfig'],
       'kernel_blacklist': ['v3.'],
       'nfs_blacklist': [],
       'lpae': False,
       'fastboot': False,
       'defconfig_whitelist': ['defconfig'],
       'mach': 'socionext'}

device_map = {'alpine-db.dtb': [alpine_db],
              'bcm2836-rpi-2-b.dtb' : [ bcm2836_rpi_2_b],
              'bcm2837-rpi-3-b.dtb' : [ bcm2837_rpi_3_b, bcm2837_rpi_3_b_32],
              'armada-370-db.dtb': [armada_370_db],
              'orion5x-rd88f5182-nas.dtb': [orion5x_rd88f5182_nas],
              'armada-370-rd.dtb': [armada_370_rd],
              'armada-375-db.dtb': [armada_375_db],
              'armada-385-db-ap.dtb': [armada_385_db_ap],
              'armada-388-gp.dtb': [armada_388_gp],
              'armada-398-db.dtb': [armada_398_db],
              'kirkwood-db-88f6282.dtb': [kirkwood_db_88f6282],
              'armada-3720-db.dtb': [armada_3720_db],
              'armada-7040-db.dtb': [armada_7040_db],
              'armada-8040-db.dtb': [armada_8040_db],
              'armada-xp-db.dtb': [armada_xp_db],
              'armada-xp-gp.dtb': [armada_xp_gp],
              'exynos5250-arndale.dtb': [arndale],
              'exynos5250-snow.dtb': [snow],
              'exynos5420-arndale-octa.dtb': [arndale_octa],
              'exynos5800-peach-pi.dtb': [peach_pi],
              'exynos5422-odroidxu3.dtb': [odroid_xu3],
              'exynos4412-odroidx2.dtb': [odroid_x2],
              'am335x-boneblack.dtb': [beaglebone_black],
              'omap3-beagle-xm.dtb': [beagle_xm],
              'omap4-panda-es.dtb': [panda_es],
              'omap4-panda.dtb': [panda],
              'dra7-evm.dtb' : [dra7_evm],
              'hip06-d03.dtb': [d03],
              'hip07-d05.dtb': [d05],
              'imx6ul-pico-hobbit.dtb': [imx6ul_pico_hobbit],
              'imx6q-sabrelite.dtb': [imx6q_sabrelite],
              'meson8b-odroidc1.dtb': [meson8b_odroidc1],
              'meson-gxbb-nanopi-k2.dtb': [meson_gxbb_nanopi_k2],
              'meson-gxbb-odroidc2.dtb': [meson_gxbb_odroidc2],
              'meson-gxbb-p200.dtb': [meson_gxbb_p200],
              'meson-gxl-s905x-khadas-vim.dtb': [meson_gxl_s905x_khadas_vim],
              'meson-gxl-s905x-libretech-cc.dtb': [meson_gxl_s905x_libretech_cc],
              'r8a7795-salvator-x.dtb': [r8a7795_salvator_x],
              'r8a7796-m3ulcb.dtb': [r8a7796_m3ulcb],
              'da850-lcdk.dtb': [da850_lcdk],
              'qcom-apq8064-ifc6410.dtb': [ifc6410],
              'tegra124-jetson-tk1.dtb': [jetson_tk1],
              'tegra124-nyan-big.dtb': [tegra124_nyan_big],
              'zynq-zc702.dtb': [zynq_zc702],
              'rk3288-rock2-square.dtb': [rk3288_rock2_square],
              'rk3288-veyron-jaq.dtb': [rk3288_veyron_jaq],
              'rk3399-gru-kevin.dtb': [rk3399_gru_kevin],
              'rk3399-puma-haikou.dtb': [rk3399_puma_haikou],
              'qemu': [qemu],
              'apq8016-sbc.dtb': [apq8016_sbc],
              'apm-mustang.dtb': [apm_mustang],
              'x86': [minnowboard_max_E3825, x86_atom330, x86_x5_z8350],
              'x86-32': [x86_pentium4, x86_celeron],
              'imx6dl-riotboard.dtb': [imx6dl_riotboard],
              'imx53-qsrb.dtb': [imx53_qsbr],
              'imx28-duckbill.dtb': [imx28_duckbill],
              'imx23-olinuxino.dtb': [imx23_olinuxino],
              'socfpga_cyclone5_socrates.dtb': [socfpga_cyclone5_socrates],
              'imx27-phytec-phycard-s-rdk.dtb': [imx27_phycard_s],
              'armada-xp-linksys-mamba.dtb': [armada_xp_linksys_mamba],
              'armada-388-clearfog.dtb': [armada_388_clearfog],
              'sun5i-gr8-chip-pro.dtb': [chip_pro],
              'sun5i-r8-chip.dtb': [chip],
              'imx6q-nitrogen6x.dtb': [imx6q_nitrogen6x],
              'at91sam9261ek.dtb': [sam9261ek],
              'at91sam9x25ek.dtb': [sam9x25ek],
              'at91sam9x35ek.dtb': [at91sam9x35ek],
              'at91rm9200ek.dtb': [at91rm9200ek],
              'at91-sama5d2_xplained.dtb': [at91_sama5d2_xplained],
              'at91-sama5d4_xplained.dtb': [at91_sama5d4_xplained],
              'at91sam9m10g45ek.dtb': [at91sam9m10g45ek],
              'sun50i-h5-libretech-all-h3-cc.dtb': [sun50i_h5_libretech_all_h3_cc],
              'sun8i-a23-evb.dtb': [sun8i_a23_evb],
              'sun8i-a83t-allwinner-h8homlet-v2.dtb': [sun8i_a83t_allwinner_h8homlet_v2],
              'sun8i-h2-plus-libretech-all-h3-cc.dtb': [sun8i_h2_plus_libretech_all_h3_cc],
              'sun8i-h3-orangepi-pc.dtb': [sun8i_h3_orangepi_pc],
              'sun8i-h3-libretech-all-h3-cc.dtb': [sun8i_h3_libretech_all_h3_cc],
              'sun8i-a33-sinlinx-sina33.dtb': [sinlinx_sina33],
              'kirkwood-openblocks_a7.dtb': [openblocks_a7],
              'armada-xp-openblocks-ax3-4.dtb': [openblocks_ax3],
              'dove-cubox.dtb' : [dove_cubox],
              'r8a7791-porter.dtb': [r8a7791_porter],
              'arm64-no-dtb': [synquacer_acpi, synquacer_dtb]}
