alpine_db = {'device_type': 'alpine-db',
                      'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                      'kernel_defconfig_blacklist': [],
                      'defconfig_blacklist': ['arm-allmodconfig'],
                      'kernel_blacklist': [],
                      'nfs_blacklist': [],
                      'lpae': False,
                      'fastboot': False}

alpine_v2_evp = {'device_type': 'alpine-v2-evp',
                      'templates': ['generic-arm64-dtb-kernel-ci-boot-template.json'],
                      'kernel_defconfig_blacklist': [],
                      'defconfig_blacklist': ['arm64-allmodconfig'],
                      'kernel_blacklist': [],
                      'nfs_blacklist': [],
                      'lpae': False,
                      'fastboot': False}

bcm2835_rpi_b_plus = {'device_type': 'bcm2835-rpi-b-plus',
                      'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                      'kernel_defconfig_blacklist': [],
                      'defconfig_blacklist': ['arm-allmodconfig'],
                      'kernel_blacklist': [],
                      'nfs_blacklist': [],
                      'lpae': False,
                      'fastboot': False}

bcm2836_rpi_2_b = {'device_type': 'bcm2836-rpi-2-b',
                      'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                      'kernel_defconfig_blacklist': [],
                      'defconfig_blacklist': ['arm-allmodconfig'],
                      'kernel_blacklist': [],
                      'nfs_blacklist': [],
                      'lpae': False,
                      'fastboot': False}

bcm4708_smartrg_sr400ac = {'device_type': 'bcm4708-smartrg-sr400ac',
                           'templates': ['cfe-arm-dtb-kernel-ci-boot-template.json',
                                         'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                           'kernel_defconfig_blacklist': [],
                           'defconfig_blacklist': ['arm-allmodconfig',
                                                   'arm-multi_v7_defconfig+CONFIG_PROVE_LOCKING=y'],
                           'kernel_blacklist': ['v3.18',
                                                'v4.1',
                                                'v4.2',
                                                'lsk-v3.18',
                                                'lsk-v4.1',
                                                'stable-queue-v4.2'],
                           'nfs_blacklist': [],
                           'lpae': False,
                           'fastboot': False}

armada_370_db = {'device_type': 'armada-370-db',
                       'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['arm-allmodconfig'],
                       'kernel_blacklist': ['v3'],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False}

armada_370_mirabox = {'device_type': 'armada-370-mirabox',
                       'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                     'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['arm-allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False}

orion5x_rd88f5182_nas = {'device_type': 'orion5x-rd88f5182-nas',
                       'templates': ['generic-arm-dtb-kernel-ci-boot-nfs-template.json'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['arm-allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False}

armada_370_rd = {'device_type': 'armada-370-rd',
                       'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
		       'kernel_defconfig_blacklist': [{'kernel_version': 'v4.0', 'defconfig': 'arm-multi_v7_defconfig'},
						      {'kernel_version': 'v4.1', 'defconfig': 'arm-multi_v7_defconfig'},
						      {'kernel_version': 'v4.2', 'defconfig': 'arm-multi_v7_defconfig'},
						      {'kernel_version': 'v4.3', 'defconfig': 'arm-multi_v7_defconfig'}],
                       'defconfig_blacklist': ['arm-allmodconfig'],
                       'kernel_blacklist': ['v3'],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False}

armada_375_db = {'device_type': 'armada-375-db',
                       'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['arm-allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False}

armada_385_db_ap = {'device_type': 'armada-385-db-ap',
                       'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['arm-allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False}

armada_388_gp = {'device_type': 'armada-388-gp',
                       'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['arm-allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False}

armada_398_db = {'device_type': 'armada-398-db',
                       'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['arm-allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False}

kirkwood_db_88f6282 = {'device_type': 'kirkwood-db-88f6282',
                       'templates': ['generic-arm-dtb-kernel-ci-boot-nfs-template.json'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['arm-allmodconfig',
			# To be removed once NFS is working for this defconfig
					       'arm-multi_v5_defconfig'],
                       'kernel_blacklist': ['v3'],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False}

armada_3720_db = {'device_type': 'armada-3720-db',
                       'templates': ['generic-arm64-dtb-kernel-ci-boot-template.json'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['arm64-allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False}

armada_7040_db = {'device_type': 'armada-7040-db',
                       'templates': ['generic-arm64-dtb-kernel-ci-boot-template.json'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['arm64-allmodconfig'],
                       'kernel_blacklist': ['v4.6'],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False}

armada_xp_db = {'device_type': 'armada-xp-db',
                       'templates': ['generic-arm-dtb-kernel-ci-boot-nfs-template.json'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['arm-allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False}

armada_xp_gp = {'device_type': 'armada-xp-gp',
                       'templates': ['generic-arm-dtb-kernel-ci-boot-nfs-template.json'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['arm-allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False}

arndale = {'device_type': 'arndale',
           'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                         'generic-arm-dtb-kernel-ci-kselftest-template.json',
                         'generic-arm-dtb-kernel-ci-hackbench-template.json'],
           'kernel_defconfig_blacklist': [],
           'defconfig_blacklist': ['arm-allmodconfig',
                                   'arm-multi_v7_defconfig+CONFIG_SMP=n'],
           'kernel_blacklist': [],
           'nfs_blacklist': [],
           'lpae': True,
           'fastboot': False}

snow = {'device_type': 'snow',
        'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                      'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                      'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                      'generic-arm-dtb-kernel-ci-kselftest-template.json',
                      'generic-arm-dtb-kernel-ci-hackbench-template.json'],
        'kernel_defconfig_blacklist': [],
        'defconfig_blacklist': ['arm-allmodconfig'],
        'kernel_blacklist': [],
        'nfs_blacklist': [],
        'lpae': True,
        'fastboot': False}

arndale_octa = {'device_type': 'arndale-octa',
                'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                              'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                              'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                              'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                'kernel_defconfig_blacklist': [],
                'defconfig_blacklist': ['arm-allmodconfig',
                                        'arm-multi_v7_defconfig+linaro-base+distribution'],
                'kernel_blacklist': [],
                'nfs_blacklist': ['v3.',
                                  'lsk-v3.'],
                'lpae': True,
                'fastboot': False}

peach_pi = {'device_type': 'peach-pi',
            'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                          'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                          'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                          'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                          'generic-arm-dtb-kernel-ci-kselftest-template.json',
                          'generic-arm-dtb-kernel-ci-hackbench-template.json'],
            'kernel_defconfig_blacklist': [],
            'defconfig_blacklist': ['arm-allmodconfig'],
            'kernel_blacklist': [],
            'nfs_blacklist': ['v3.',
                              'lsk-v3.'],
            'lpae': True,
            'fastboot': False}

odroid_xu3 = {'device_type': 'odroid-xu3',
              'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                            'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                            'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                            'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                            'generic-arm-dtb-kernel-ci-kselftest-template.json',
                            'generic-arm-dtb-kernel-ci-hackbench-template.json'],
              'kernel_defconfig_blacklist': [],
              'defconfig_blacklist': ['arm-allmodconfig'],
              'kernel_blacklist': [],
              'nfs_blacklist': [],
              'lpae': True,
              'fastboot': False}

odroid_u2 = {'device_type': 'odroid-u2',
             'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                           'generic-arm-dtb-kernel-ci-kselftest-template.json'],
             'kernel_defconfig_blacklist': [],
             'defconfig_blacklist': ['arm-allmodconfig',
                                     'arm-multi_v7_defconfig+CONFIG_THUMB2_KERNEL=y',
                                     'arm-multi_v7_defconfig+linaro-base+distribution'],
             'kernel_blacklist': [],
             'nfs_blacklist': [],
             'lpae': False,
             'fastboot': False}

odroid_x2 = {'device_type': 'odroid-x2',
             'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                           'generic-arm-dtb-kernel-ci-kselftest-template.json'],
             'kernel_defconfig_blacklist': [],
             'defconfig_blacklist': ['arm-allmodconfig'],
             'kernel_blacklist': [],
             'nfs_blacklist': [],
             'lpae': False,
             'fastboot': False}

beaglebone_black = {'device_type': 'beaglebone-black',
                    'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                  'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                                  'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                                  'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                                  'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                                  'generic-arm-dtb-kernel-ci-kselftest-template.json',
                                  'generic-arm-dtb-kernel-ci-hackbench-template.json'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['arm-allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False}

beagle_xm = {'device_type': 'beagle-xm',
             'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                           'generic-arm-dtb-kernel-ci-kselftest-template.json',
                           'generic-arm-dtb-kernel-ci-hackbench-template.json'],
             'kernel_defconfig_blacklist': [],
             'defconfig_blacklist': ['arm-allmodconfig'],
             'kernel_blacklist': ['v3.14',
                                  'lsk-v3.14'],
             'nfs_blacklist': [],
             'lpae': False,
             'fastboot': False}

omap3_overo_tobi = {'device_type': 'omap3-overo-tobi',
                    'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                  'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['arm-allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False}

omap3_overo_storm_tobi = {'device_type': 'omap3-overo-storm-tobi',
                          'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                        'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                          'kernel_defconfig_blacklist': [],
                          'defconfig_blacklist': ['arm-allmodconfig'],
                          'kernel_blacklist': [],
                          'nfs_blacklist': [],
                          'lpae': False,
                          'fastboot': False}

panda_es = {'device_type': 'panda-es',
            'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                          'generic-arm-dtb-kernel-ci-kselftest-template.json',
                          'generic-arm-dtb-kernel-ci-hackbench-template.json'],
            'kernel_defconfig_blacklist': [],
            'defconfig_blacklist': ['arm-allmodconfig'],
            'kernel_blacklist': [],
            'nfs_blacklist': [],
            'lpae': False,
            'fastboot': False}

panda = {'device_type': 'panda',
         'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                       'generic-arm-dtb-kernel-ci-kselftest-template.json',
                       'generic-arm-dtb-kernel-ci-hackbench-template.json'],
         'kernel_defconfig_blacklist': [],
         'defconfig_blacklist': ['arm-allmodconfig'],
         'kernel_blacklist': [],
         'nfs_blacklist': [],
         'lpae': False,
         'fastboot': False}

omap5_uevm = {'device_type': 'omap5-uevm',
              'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                            'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                            'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                            'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                            'generic-arm-dtb-kernel-ci-kselftest-template.json'],
              'kernel_defconfig_blacklist': [],
              'defconfig_blacklist': ['arm-allmodconfig'],
              'kernel_blacklist': [],
              'nfs_blacklist': [],
              'lpae': True,
              'fastboot': False}

cubieboard2 = {'device_type': 'cubieboard2',
               'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                             'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                             'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                             'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                             'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                             'generic-arm-dtb-kernel-ci-cpufreq-ljt-stress-test-template.json',
                             'generic-arm-dtb-kernel-ci-kselftest-template.json'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['arm-allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': ['v3.10',
                                 'lsk-v3.10',
                                 'v3.14',
                                 'lsk-v3.14',
                                 'v4.5'],
               'lpae': True,
               'be': False,
               'fastboot': False}

cubieboard3 = {'device_type': 'cubieboard3',
               'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                             'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                             'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                             'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                             'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                             'generic-arm-dtb-kernel-ci-cpufreq-ljt-stress-test-template.json',
                             'generic-arm-dtb-kernel-ci-kselftest-template.json',
                             'generic-arm-dtb-kernel-ci-hackbench-template.json'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['arm-allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': ['v3.10',
                                 'lsk-v3.10',
                                 'v3.14',
                                 'lsk-v3.14'],
               'lpae': True,
               'be': False,
               'fastboot': False}

cubieboard3_kvm = {'device_type': 'cubieboard3',
                   'templates': ['generic-arm-boot-kvm-template.json'],
                   'kernel_defconfig_blacklist': [],
                   'defconfig_blacklist': [],
                   'kernel_blacklist': [],
                   'nfs_blacklist': [],
                   'lpae': True,
                   'fastboot': False}

sun7i_a20_bananapi = {'device_type': 'sun7i-a20-bananapi',
                      'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                    'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                                    'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                                    'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                                    'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                                    'generic-arm-dtb-kernel-ci-cpufreq-ljt-stress-test-template.json',
                                    'generic-arm-dtb-kernel-ci-kselftest-template.json',
                                    'generic-arm-dtb-kernel-ci-hackbench-template.json'],
                      'kernel_defconfig_blacklist': [],
                      'defconfig_blacklist': ['arm-allmodconfig'],
                      'kernel_blacklist': [],
                      'nfs_blacklist': [],
                      'lpae': True,
                      'be': False,
                      'fastboot': False}

hisi_x5hd2_dkb = {'device_type': 'hi3716cv200',
                  'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                                'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                                'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                                'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                                'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                  'kernel_defconfig_blacklist': [],
                  'defconfig_blacklist': ['arm-allmodconfig'],
                  'kernel_blacklist': [],
                  'nfs_blacklist': ['v3.',
                                    'lsk-v3.'],
                  'lpae': False,
                  'fastboot': False}

d01 = {'device_type': 'd01',
       'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                     'generic-arm-dtb-kernel-ci-kselftest-template.json'],
       'kernel_defconfig_blacklist': [],
       'defconfig_blacklist': ['arm-allmodconfig',
                               'arm-multi_v7_defconfig+linaro-base+distribution'],
       'kernel_blacklist': [],
       'nfs_blacklist': [],
       'lpae': True,
       'fastboot': False}

imx6q_wandboard = {'device_type': 'imx6q-wandboard',
                   'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                 'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                                 'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                                 'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                                 'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                                 'generic-arm-dtb-kernel-ci-kselftest-template.json',
                                 'generic-arm-dtb-kernel-ci-hackbench-template.json'],
                   'kernel_defconfig_blacklist': [],
                   'defconfig_blacklist': ['arm-imx_v4_v5_defconfig',
                                           'arm-multi_v5_defconfig',
                                           'arm-allmodconfig'],
                   'kernel_blacklist': [],
                   'nfs_blacklist': [],
                   'lpae': False,
                   'fastboot': False}

imx6q_sabrelite = {'device_type': 'imx6q-sabrelite',
                   'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                 'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                                 'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                                 'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                                 'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                                 'generic-arm-dtb-kernel-ci-kselftest-template.json',
                                 'generic-arm-dtb-kernel-ci-hackbench-template.json'],
                   'kernel_defconfig_blacklist': [],
                   'defconfig_blacklist': ['arm-imx_v4_v5_defconfig',
                                           'arm-imx_v6_v7_defconfig',
                                           'arm-multi_v5_defconfig',
                                           'arm-allmodconfig'],
                   'kernel_blacklist': ['v3.18',
                                        'lsk-v3.18'],
                   'nfs_blacklist': [],
                   'lpae': False,
                   'fastboot': False}

utilite_pro = {'device_type': 'utilite-pro',
               'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                             'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                             'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                             'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                             'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                             'generic-arm-dtb-kernel-ci-kselftest-template.json',
                             'generic-arm-dtb-kernel-ci-hackbench-template.json'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['arm-imx_v4_v5_defconfig',
                                       'arm-multi_v5_defconfig',
                                       'arm-allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': [],
               'lpae': False,
               'fastboot': False}

meson8b_odroidc1 = {'device_type': 'meson8b-odroidc1',
                    'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                  'generic-arm-dtb-kernel-ci-kselftest-template.json',
                                  'generic-arm-dtb-kernel-ci-hackbench-template.json'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['arm-allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False}

da850_lcdk = {'device_type': 'da850-lcdk',
                    'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                  'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                                  'generic-arm-dtb-kernel-ci-kselftest-template.json',
                                  'generic-arm-dtb-kernel-ci-hackbench-template.json'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['arm-allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False}

snowball = {'device_type': 'snowball',
            'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                          'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                          'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                          'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                          'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                          'generic-arm-dtb-kernel-ci-kselftest-template.json',
                          'generic-arm-dtb-kernel-ci-hackbench-template.json'],
            'kernel_defconfig_blacklist': [],
            'defconfig_blacklist': ['arm-allmodconfig'],
            'kernel_blacklist': [],
            'nfs_blacklist': [],
            'lpae': False,
            'fastboot': False}

ifc6540 = {'device_type': 'ifc6540',
           'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                         'generic-arm-dtb-kernel-ci-kselftest-template.json',
                         'generic-arm-dtb-kernel-ci-hackbench-template.json'],
           'kernel_defconfig_blacklist': [],
           'defconfig_blacklist': ['arm-allmodconfig'],
           'kernel_blacklist': [],
           'nfs_blacklist': [],
           'lpae': False,
           'fastboot': True}

ifc6410 = {'device_type': 'ifc6410',
           'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                         'generic-arm-dtb-kernel-ci-kselftest-template.json',
                         'generic-arm-dtb-kernel-ci-hackbench-template.json'],
           'kernel_defconfig_blacklist': [],
           'defconfig_blacklist': ['arm-allmodconfig'],
           'kernel_blacklist': [],
           'nfs_blacklist': [],
           'lpae': False,
           'fastboot': True}

highbank = {'device_type': 'highbank',
            'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                          'generic-arm-dtb-kernel-ci-kselftest-template.json',
                          'generic-arm-dtb-kernel-ci-hackbench-template.json'],
            'kernel_defconfig_blacklist': [],
            'defconfig_blacklist': ['arm-allmodconfig',
                                    'arm-multi_v7_defconfig+CONFIG_SMP=n'],
            'kernel_blacklist': [],
            'nfs_blacklist': [],
            'lpae': False,
            'fastboot': True}

sama53d = {'device_type': 'sama53d',
           'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                         'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                         'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                         'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                         'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                         'generic-arm-dtb-kernel-ci-kselftest-template.json'],
           'kernel_defconfig_blacklist': [],
           'defconfig_blacklist': ['arm-at91_dt_defconfig',
                                   'arm-at91sam9260_9g20_defconfig',
                                   'arm-at91sam9g45_defconfig',
                                   'arm-allmodconfig'],
           'kernel_blacklist': [],
           'nfs_blacklist': [],
           'lpae': False,
           'fastboot': False}

jetson_tk1 = {'device_type': 'jetson-tk1',
              'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                            'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                            'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                            'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                            'generic-arm-dtb-kernel-ci-kselftest-template.json',
                            'generic-arm-dtb-kernel-ci-hackbench-template.json'],
              'kernel_defconfig_blacklist': [],
              'defconfig_blacklist': ['arm-allmodconfig'],
              'kernel_blacklist': [],
              'nfs_blacklist': [],
              'lpae': True,
              'fastboot': False}

tegra124_nyan_big = {'device_type': 'tegra124-nyan-big',
                     'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                   'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                                   'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                                   'generic-arm-dtb-kernel-ci-kselftest-template.json',
                                   'generic-arm-dtb-kernel-ci-hackbench-template.json'],
                     'kernel_defconfig_blacklist': [],
                     'defconfig_blacklist': ['arm-allmodconfig'],
                     'kernel_blacklist': [],
                     'nfs_blacklist': [],
                     'lpae': True,
                     'fastboot': False}

parallella = {'device_type': 'parallella',
              'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                            'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                            'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                            'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                            'generic-arm-dtb-kernel-ci-kselftest-template.json'],
              'kernel_defconfig_blacklist': [],
              'defconfig_blacklist': ['arm-allmodconfig',
                                      'arm-multi_v7_defconfig+linaro-base+distribution'],
              'kernel_blacklist': [],
              'nfs_blacklist': [],
              'lpae': False,
              'fastboot': False}

zynq_zc702 = {'device_type': 'zynq-zc702',
              'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
              'kernel_defconfig_blacklist': [],
              'defconfig_blacklist': ['arm-allmodconfig',
                                      'arm-multi_v7_defconfig+linaro-base+distribution'],
              'kernel_blacklist': [],
              'nfs_blacklist': [],
              'lpae': False,
              'fastboot': False}

optimus_a80 = {'device_type': 'optimus-a80',
               'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                             'generic-arm-dtb-kernel-ci-kselftest-template.json'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['arm-allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': [],
               'lpae': True,
               'fastboot': True}

cubieboard4 = {'device_type': 'cubieboard4',
               'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                             'generic-arm-dtb-kernel-ci-kselftest-template.json'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['arm-allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': [],
               'lpae': True,
               'fastboot': True}

rk3288_rock2_square = {'device_type': 'rk3288-rock2-square',
                       'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                     'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                                     'generic-arm-dtb-kernel-ci-kselftest-template.json',
                                     'generic-arm-dtb-kernel-ci-hackbench-template.json'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['arm-allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': True,
                       'fastboot': True}

zx296702_ad1 = {'device_type': 'zx296702-ad1',
                'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                              'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                'kernel_defconfig_blacklist': [],
                'defconfig_blacklist': ['arm-allmodconfig'],
                'kernel_blacklist': [],
                'nfs_blacklist': [],
                'lpae': False,
                'fastboot': True}

vf610_zii_dev_rev_b = {'device_type': 'vf610-zii-dev-rev-b',
                       'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                     'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                                     'generic-arm-dtb-kernel-ci-kselftest-template.json',
                                     'generic-arm-dtb-kernel-ci-hackbench-template.json'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['arm-allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': True}

qemu_arm_cortex_a9 = {'device_type': 'qemu-arm-cortex-a9',
                      'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                    'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                      'kernel_defconfig_blacklist': [],
                      'defconfig_blacklist': ['arm-allmodconfig'],
                      'kernel_blacklist': [],
                      'nfs_blacklist': [],
                      'lpae': False,
                      'fastboot': False}

qemu_arm_cortex_a9_legacy = {'device_type': 'qemu-arm-cortex-a9',
                             'templates': ['generic-arm-kernel-ci-boot-template.json',
                                           'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                             'kernel_defconfig_blacklist': [],
                             'defconfig_blacklist': ['arm-allmodconfig'],
                             'kernel_blacklist': [],
                             'nfs_blacklist': [],
                             'lpae': False,
                             'fastboot': False}

qemu_arm_cortex_a15_a7 = {'device_type': 'qemu-arm-cortex-a15',
                          'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                        'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                          'kernel_defconfig_blacklist': [],
                          'defconfig_blacklist': ['arm-allmodconfig'],
                          'kernel_blacklist': [],
                          'nfs_blacklist': [],
                          'lpae': True,
                          'fastboot': False}

qemu_arm_cortex_a15 = {'device_type': 'qemu-arm-cortex-a15',
                       'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                     'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['arm-allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': True,
                       'fastboot': False}

qemu_arm_cortex_a15_legacy = {'device_type': 'qemu-arm-cortex-a15',
                              'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                            'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                              'kernel_defconfig_blacklist': [],
                              'defconfig_blacklist': ['arm-allmodconfig'],
                              'kernel_blacklist': [],
                              'nfs_blacklist': [],
                              'lpae': True,
                              'fastboot': False}

qemu_aarch64 = {'device_type': 'qemu-aarch64',
                'templates': ['generic-arm64-kernel-ci-boot-template.json',
                              'generic-arm64-kernel-ci-kselftest-template.json'],
                'kernel_defconfig_blacklist': [],
                'defconfig_blacklist': ['arm64-allnoconfig',
                                        'arm64-allmodconfig'],
                'kernel_blacklist': [],
                'nfs_blacklist': [],
                'lpae': False,
                'fastboot': False}

apq8016_sbc = {'device_type': 'apq8016-sbc',
               'templates': ['generic-arm64-dtb-kernel-ci-boot-template.json',
                             'generic-arm64-dtb-kernel-ci-boot-be-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-cyclictest-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-hackbench-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-lmbench-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-ltp-realtime-template.json',
                             'generic-arm64-dtb-kernel-ci-kselftest-template.json'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['arm64-allnoconfig',
                                       'arm64-allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': [],
               'lpae': False,
               'fastboot': True}

apm_mustang = {'device_type': 'mustang',
               'templates': ['generic-arm64-dtb-kernel-ci-boot-template.json',
                             'generic-arm64-dtb-kernel-ci-boot-nfs-template.json',
                             'generic-arm64-dtb-kernel-ci-boot-be-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-cyclictest-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-cyclictest-basic-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-hackbench-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-lmbench-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-ltp-mm-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-ltp-realtime-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-ltp-syscalls-template.json',
                             'generic-arm64-dtb-kernel-ci-kselftest-template.json'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['arm64-allnoconfig',
                                       'arm64-allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': ['v3.10',
                                 'lsk-v3.10',
                                 'v3.12',
                                 'v3.14',
                                 'lsk-v3.14',
                                 'v3.18'],
               'be_blacklist': ['v3.10'],
               'lpae': False,
               'fastboot': False}

apm_mustang_kvm = {'device_type': 'mustang',
                   'templates': ['generic-arm64-boot-kvm-template.json',
                                 'generic-arm64-boot-kvm-uefi-template.json'],
                   'kernel_defconfig_blacklist': [],
                   'defconfig_blacklist': ['arm64-allnoconfig',
                                           'arm64-allmodconfig'],
                   'kernel_blacklist': ['v3.10',
                                        'lsk-v3.10',
                                        'v3.12',
                                        'lsk-v3.12',
                                        'v3.14',
                                        'lsk-v3.14',
                                        'v3.18',
                                        'lsk-v3.18'],
                   'nfs_blacklist': [],
                   'lpae': False,
                   'fastboot': False}

juno = {'device_type': 'juno',
        'templates': ['juno-arm64-dtb-kernel-ci-boot-template.json',
                      'generic-arm64-dtb-kernel-ci-boot-nfs-template.json',
                      'juno-arm64-dtb-kernel-ci-ltp-mm-template.json',
                      'juno-arm64-dtb-kernel-ci-kselftest-template.json'],
        'kernel_defconfig_blacklist': [],
        'defconfig_blacklist': ['arm64-allnoconfig',
                                'arm64-allmodconfig'],
        'kernel_blacklist': [],
        'nfs_blacklist': [],
        'lpae': False,
        'fastboot': False}

fvp_aemv8a = {'device_type': 'rtsm_fvp_base-aemv8a',
              'templates': ['generic-arm64-dtb-uefi-kernel-ci-boot-template.json',
                            'generic-arm64-dtb-kernel-ci-kselftest-template.json'],
              'kernel_defconfig_blacklist': [],
              'defconfig_blacklist': ['arm64-allnoconfig',
                                      'arm64-allmodconfig',
                                      'arm64-defconfig+kvm-host',
                                      'arm64-defconfig+kvm-guest'],
              'kernel_blacklist': [],
              'nfs_blacklist': [],
              'lpae': False,
              'fastboot': False}

juno_kvm = {'device_type': 'juno',
            'templates': ['generic-arm64-boot-kvm-template.json',
                          'generic-arm64-boot-kvm-uefi-template.json'],
            'kernel_defconfig_blacklist': [],
            'defconfig_blacklist': ['arm64-allnoconfig',
                                    'arm64-allmodconfig'],
            'kernel_blacklist': ['v3.10',
                                 'lsk-v3.10',
                                 'v3.12',
                                 'lsk-v3.12',
                                 'v3.14',
                                 'lsk-v3.14',
                                 'v3.18',
                                 'lsk-v3.18'],
            'nfs_blacklist': [],
            'lpae': False,
            'fastboot': False}

hi6220_hikey = {'device_type': 'hi6220-hikey',
                'templates': ['generic-arm64-dtb-kernel-ci-boot-template.json',
                              'generic-arm64-dtb-kernel-ci-kselftest-template.json',
                              'generic-arm64-uboot-dtb-kernel-ci-hackbench-template.json'],
                'kernel_defconfig_blacklist': [],
                'defconfig_blacklist': ['arm64-allnoconfig',
                                        'arm64-allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': [],
               'lpae': False,
               'fastboot': False}

fsl_ls2080a_rdb = {'device_type': 'fsl-ls2085a-rdb',
                   'templates': ['generic-arm64-dtb-kernel-ci-boot-template.json',
                                 'generic-arm64-dtb-kernel-ci-boot-be-template.json',
                                 'generic-arm64-dtb-kernel-ci-kselftest-template.json',
                                 'generic-arm64-uboot-dtb-kernel-ci-hackbench-template.json'],
                   'kernel_defconfig_blacklist': [],
                   'defconfig_blacklist': ['arm64-allnoconfig',
                                           'arm64-allmodconfig'],
                   'kernel_blacklist': ['v4.1',
                                        'lsk-v4.1',
                                        'stable-queue-v4.1'],
                   'nfs_blacklist': [],
                   'lpae': False,
                   'fastboot': False}

fsl_ls2080a_simu = {'device_type': 'fsl-ls2085a-rdb',
                   'templates': ['generic-arm64-dtb-kernel-ci-boot-template.json',
                                 'generic-arm64-dtb-kernel-ci-boot-be-template.json',
                                 'generic-arm64-dtb-kernel-ci-kselftest-template.json',
                                 'generic-arm64-uboot-dtb-kernel-ci-hackbench-template.json'],
                   'kernel_defconfig_blacklist': [],
                   'defconfig_blacklist': ['arm64-allnoconfig',
                                           'arm64-allmodconfig'],
                   'kernel_blacklist': ['v4.1',
                                        'lsk-v4.1',
                                        'stable-queue-v4.1'],
                   'nfs_blacklist': [],
                   'lpae': False,
                   'fastboot': False}

x86 = {'device_type': 'x86',
       'templates': ['generic-x86-kernel-ci-boot-template.json',
                     'generic-x86-kernel-ci-kselftest-template.json',
                     'generic-x86-kernel-ci-hackbench-template.json'],
       'kernel_defconfig_blacklist': [],
       'defconfig_blacklist': ['x86-i386_defconfig',
                               'x86-allnoconfig',
                               'x86-allmodconfig',
                               'x86-allmodconfig+CONFIG_OF=n',
                               'x86-tinyconfig',
                               'x86-kvm_guest.config'],
       'kernel_blacklist': [],
       'nfs_blacklist': [],
       'lpae': False,
       'fastboot': False}

x86_atom330 = {'device_type': 'x86-atom330',
                         'templates': ['generic-x86-kernel-ci-boot-template.json',
                                       'generic-x86-kernel-ci-kselftest-template.json',
                                       'generic-x86-kernel-ci-hackbench-template.json'],
                         'kernel_defconfig_blacklist': [],
                         'defconfig_blacklist': ['x86-i386_defconfig',
                                                 'x86-allnoconfig',
                                                 'x86-allmodconfig',
                                                 'x86-allmodconfig+CONFIG_OF=n',
                                                 'x86-tinyconfig',
                                                 'x86-kvm_guest.config'],
                         'kernel_blacklist': [],
                         'nfs_blacklist': [],
                         'lpae': False,
                         'fastboot': False}

minnowboard_max_E3825 = {'device_type': 'minnowboard-max-E3825',
                         'templates': ['generic-x86-kernel-ci-boot-template.json',
                                       'generic-x86-kernel-ci-cyclictest-template.json',
                                       'generic-x86-kernel-ci-kselftest-template.json',
                                       'generic-x86-kernel-ci-hackbench-template.json',
                                       'generic-x86-kernel-ci-lmbench-template.json',
                                       'generic-x86-kernel-ci-ltp-realtime-template.json'],
                         'kernel_defconfig_blacklist': [],
                         'defconfig_blacklist': ['x86-i386_defconfig',
                                                 'x86-allnoconfig',
                                                 'x86-allmodconfig',
                                                 'x86-allmodconfig+CONFIG_OF=n',
                                                 'x86-tinyconfig',
                                                 'x86-kvm_guest.config'],
                         'kernel_blacklist': [],
                         'nfs_blacklist': [],
                         'lpae': False,
                         'fastboot': False}

x86_kvm = {'device_type': 'kvm',
           'templates': ['generic-x86-kernel-ci-boot-template.json',
                         'generic-x86-kernel-ci-kselftest-template.json',
                         'generic-x86-kernel-ci-hackbench-template.json'],
           'kernel_defconfig_blacklist': [],
           'defconfig_blacklist': ['x86-i386_defconfig',
                                   'x86-allnoconfig',
                                   'x86-allmodconfig',
                                   'x86-allmodconfig+CONFIG_OF=n',
                                   'x86-tinyconfig',
                                   'x86-kvm_guest.config'],
           'kernel_blacklist': ['v3.10',
                                'lsk-v3.10'],
           'nfs_blacklist': [],
           'lpae': False,
           'fastboot': False}

qemu_i386 = {'device_type': 'qemu-i386',
             'templates': ['generic-x86-kernel-ci-boot-template.json',
                           'generic-x86-kernel-ci-kselftest-template.json',
                           'generic-x86-kernel-ci-hackbench-template.json'],
             'kernel_defconfig_blacklist': [],
             'defconfig_blacklist': ['x86-x86_64_defconfig',
                                     'x86-defconfig+CONFIG_LKDTM=y',
                                     'x86-defconfig+CONFIG_OF_UNITTEST=y',
                                     'x86-defconfig+kvm_guest',
                                     'x86-allnoconfig',
                                     'x86-allmodconfig',
                                     'x86-allmodconfig+CONFIG_OF=n',
                                     'x86-tinyconfig',
                                     'x86-kvm_guest.config'],
             'kernel_blacklist': ['v3.10',
                                  'lsk-v3.10'],
             'nfs_blacklist': [],
             'lpae': False,
             'fastboot': False}

imx6dl_riotboard = {'device_type': 'imx6dl-riotboard',
                    'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                  'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                                  'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                                  'generic-arm-dtb-kernel-ci-kselftest-template.json',
                                  'generic-arm-dtb-kernel-ci-hackbench-template.json'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['arm-imx_v4_v5_defconfig',
                                            'arm-multi_v5_defconfig',
                                            'arm-allmodconfig',
                                            'arm-multi_v7_defconfig+CONFIG_EFI=y'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False}

imx53_qsbr = {'device_type': 'imx53-qsbr',
              'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                            'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                            'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                            'generic-arm-dtb-kernel-ci-kselftest-template.json',
                            'generic-arm-dtb-kernel-ci-hackbench-template.json'],
              'kernel_defconfig_blacklist': [],
              'defconfig_blacklist': ['arm-imx_v4_v5_defconfig',
                                      'arm-multi_v5_defconfig',
                                      'arm-allmodconfig',
                                      'arm-multi_v7_defconfig+CONFIG_EFI=y'],
              'kernel_blacklist': [],
              'nfs_blacklist': [],
              'lpae': False,
              'fastboot': False}

imx28_duckbill = {'device_type': 'imx28-duckbill',
                  'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                  'kernel_defconfig_blacklist': [],
                  'defconfig_blacklist': ['arm-allmodconfig'],
                  'kernel_blacklist': ['v3.',
                                       'v4.0',
                                       'v4.1',
                                       'v4.2',
                                       'v4.3',
                                       'v4.4',
                                       'v4.5'],
                  'nfs_blacklist': [],
                  'lpae': False,
                  'fastboot': False}

imx23_olinuxino = {'device_type': 'imx23-olinuxino',
                   'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                   'kernel_defconfig_blacklist': [],
                   'defconfig_blacklist': ['arm-allmodconfig'],
                   'kernel_blacklist': ['v3.',
                                        'v4.0',
                                        'v4.1',
                                        'v4.2',
                                        'v4.3',
                                        'v4.4',
                                        'v4.5'],
                   'nfs_blacklist': [],
                   'lpae': False,
                   'fastboot': False}

socfpga_cyclone5_socrates = {'device_type': 'socfpga-cyclone5-socrates',
                             'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                           'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                                           'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                                           'generic-arm-dtb-kernel-ci-kselftest-template.json',
                                           'generic-arm-dtb-kernel-ci-hackbench-template.json'],
                             'kernel_defconfig_blacklist': [{'kernel_version': 'v4.5', 'defconfig': 'arm-socfpga_defconfig'},
                                                            {'kernel_version': 'v4.4', 'defconfig': 'arm-socfpga_defconfig'},
                                                            {'kernel_version': 'v4.3', 'defconfig': 'arm-socfpga_defconfig'},
                                                            {'kernel_version': 'v4.2', 'defconfig': 'arm-socfpga_defconfig'},
                                                            {'kernel_version': 'v4.1', 'defconfig': 'arm-socfpga_defconfig'},
                                                            {'kernel_version': 'v4.0', 'defconfig': 'arm-socfpga_defconfig'},
                                                            {'kernel_version': 'v3.', 'defconfig': 'arm-socfpga_defconfig'}],
                             'defconfig_blacklist': ['arm-allmodconfig',
                                                     'arm-multi_v7_defconfig+CONFIG_EFI=y'],
                             'kernel_blacklist': [],
                             'nfs_blacklist': [],
                             'lpae': False,
                             'fastboot': False}

imx27_phycard_s = {'device_type': 'imx27-phytec-phycard-s-rdk',
                   'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                   'kernel_defconfig_blacklist': [],
                   'defconfig_blacklist': ['arm-allmodconfig'],
                   'kernel_blacklist': ['v3.',
                                        'v4.0',
                                        'v4.1',
                                        'v4.2',
                                        'v4.3',
                                        'v4.4',
                                        'v4.5',
                                        'v4.6'],
                   'nfs_blacklist': [],
                   'lpae': False,
                   'fastboot': False}

openblocks_ax3 = {'device_type': 'armada-xp-openblocks-ax3-4',
                    'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['arm-allmodconfig',
                                            'arm-multi_v7_defconfig+CONFIG_SMP=n'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False}

openblocks_a7 = {'device_type': 'kirkwood-openblocks_a7',
                 'templates': ['generic-arm-dtb-kernel-ci-boot-nfs-template.json'],
                 'kernel_defconfig_blacklist': [],
                 'defconfig_blacklist': ['arm-allmodconfig',
		 # To be removed once NFS is working for this defconfig
					 'arm-multi_v5_defconfig'],
                 'kernel_blacklist': ['v3'],
                 'nfs_blacklist': [],
                 'lpae': False,
                 'fastboot': False}

armada_xp_linksys_mamba = {'device_type': 'armada-xp-linksys-mamba',
			   'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
			   'kernel_defconfig_blacklist': [],
			   'defconfig_blacklist': ['arm-allmodconfig',
						   'arm-multi_v7_defconfig+CONFIG_SMP=n'],
			   'kernel_blacklist': [],
			   'nfs_blacklist': [],
			   'lpae': False,
			   'fastboot': False}

armada_388_clearfog = {'device_type': 'armada-388-clearfog',
                    'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['arm-allmodconfig',
                                            'arm-multi_v7_defconfig+CONFIG_SMP=n'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False}

chip = {'device_type': 'sun5i-r8-chip',
                    'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['arm-allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False}

imx6q_nitrogen6x = {'device_type': 'imx6q-nitrogen6x',
                   'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                   'kernel_defconfig_blacklist': [],
                   'defconfig_blacklist': ['arm-allmodconfig',
					   'arm-imx_v4_v5_defconfig',
					   'arm-multi_v5_defconfig'],
                   'kernel_blacklist': [],
                   'nfs_blacklist': [],
                   'lpae': False,
                   'fastboot': False}

sama5d34ek = {'device_type': 'sama5d34ek',
                    'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['arm-allmodconfig',
					    'arm-at91_dt_defconfig',
					    'arm-at91rm9200_defconfig',
					    'arm-at91sam9261_9g10_defconfig',
					    'arm-at91sam9263_defconfig',
					    'arm-at91sam9g45_defconfig',
					    'arm-at91sam9rl_defconfig',
					    'arm-at91x40_defconfig',
					    'arm-at91sam9260_9g20_defconfig',
					    'arm-at91sam9260_defconfig',
					    'arm-at91sam9261_defconfig',
					    'arm-at91sam9g20_defconfig',
					    'arm-at91sam9rl_defconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False}

sama5d36ek = {'device_type': 'sama5d36ek',
                    'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['arm-allmodconfig',
					    'arm-at91_dt_defconfig',
					    'arm-at91rm9200_defconfig',
					    'arm-at91sam9261_9g10_defconfig',
					    'arm-at91sam9263_defconfig',
					    'arm-at91sam9g45_defconfig',
					    'arm-at91sam9rl_defconfig',
					    'arm-at91x40_defconfig',
					    'arm-at91sam9260_9g20_defconfig',
					    'arm-at91sam9260_defconfig',
					    'arm-at91sam9261_defconfig',
					    'arm-at91sam9g20_defconfig',
					    'arm-at91sam9rl_defconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False}

sama5d35ek = {'device_type': 'sama5d35ek',
                    'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['arm-allmodconfig',
					    'arm-at91_dt_defconfig',
					    'arm-at91rm9200_defconfig',
					    'arm-at91sam9261_9g10_defconfig',
					    'arm-at91sam9263_defconfig',
					    'arm-at91sam9g45_defconfig',
					    'arm-at91sam9rl_defconfig',
					    'arm-at91x40_defconfig',
					    'arm-at91sam9260_9g20_defconfig',
					    'arm-at91sam9260_defconfig',
					    'arm-at91sam9261_defconfig',
					    'arm-at91sam9g20_defconfig',
					    'arm-at91sam9rl_defconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False}

at91sam9m10g45ek = {'device_type': 'at91sam9m10g45ek',
                    'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['arm-allmodconfig',
					    'arm-multi_v7_defconfig',
					    'arm-at91rm9200_defconfig',
					    'arm-at91sam9261_9g10_defconfig',
					    'arm-at91sam9263_defconfig',
					    'arm-at91sam9rl_defconfig',
					    'arm-at91x40_defconfig',
					    'arm-sama5_defconfig',
					    'arm-at91sam9260_9g20_defconfig',
					    'arm-at91sam9260_defconfig',
					    'arm-at91sam9261_defconfig',
					    'arm-at91sam9g20_defconfig',
					    'arm-at91sam9rl_defconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False}

sam9261ek = {'device_type': 'at91sam9261ek',
                    'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['arm-allmodconfig',
					    'arm-multi_v7_defconfig',
					    'arm-at91rm9200_defconfig',
					    'arm-at91sam9263_defconfig',
					    'arm-at91sam9g45_defconfig',
					    'arm-at91sam9rl_defconfig',
					    'arm-at91x40_defconfig',
					    'arm-sama5_defconfig',
					    'arm-at91sam9260_9g20_defconfig',
					    'arm-at91sam9260_defconfig',
					    'arm-at91sam9g20_defconfig',
					    'arm-at91sam9rl_defconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False}

sam9x25ek = {'device_type': 'at91sam9x25ek',
                    'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['arm-allmodconfig',
					    'arm-multi_v7_defconfig',
					    'arm-at91rm9200_defconfig',
					    'arm-at91sam9261_9g10_defconfig',
					    'arm-at91sam9263_defconfig',
					    'arm-at91sam9g45_defconfig',
					    'arm-at91sam9rl_defconfig',
					    'arm-at91x40_defconfig',
					    'arm-sama5_defconfig',
					    'arm-at91sam9260_9g20_defconfig',
					    'arm-at91sam9260_defconfig',
					    'arm-at91sam9261_defconfig',
					    'arm-at91sam9g20_defconfig',
					    'arm-at91sam9rl_defconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False}

at91sam9x35ek = {'device_type': 'at91sam9x35ek',
                    'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['arm-allmodconfig',
					    'arm-multi_v7_defconfig',
					    'arm-at91rm9200_defconfig',
					    'arm-at91sam9261_9g10_defconfig',
					    'arm-at91sam9263_defconfig',
					    'arm-at91sam9g45_defconfig',
					    'arm-at91sam9rl_defconfig',
					    'arm-at91x40_defconfig',
					    'arm-sama5_defconfig',
					    'arm-at91sam9260_9g20_defconfig',
					    'arm-at91sam9260_defconfig',
					    'arm-at91sam9261_defconfig',
					    'arm-at91sam9g20_defconfig',
					    'arm-at91sam9rl_defconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False}

at91rm9200ek = {'device_type': 'at91rm9200ek',
                    'templates': ['generic-arm-dtb-kernel-ci-boot-nfs-template.json'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['arm-allmodconfig'],
                    'kernel_blacklist': ['v3'],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False}

at91_sama5d2_xplained = {'device_type': 'at91-sama5d2_xplained',
                    'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['arm-allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False}

at91_sama5d4_xplained = {'device_type': 'at91-sama5d4_xplained',
                    'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['arm-allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False}

sun8i_a83t_allwinner_h8homlet_v2 = {'device_type': 'sun8i-a83t-allwinner-h8homlet-v2',
                    'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['arm-allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False}

sinlinx_sina33 = {'device_type': 'sun8i-a33-sinlinx-sina33',
                    'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['arm-allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False}

device_map = {'alpine-db.dtb': [alpine_db],
              'alpine-v2-evp.dtb': [alpine_v2_evp],
              'bcm2835-rpi-b-plus.dtb': [bcm2835_rpi_b_plus],
              'bcm2836-rpi-2-b.dtb' : [ bcm2836_rpi_2_b],
              'bcm4708-smartrg-sr400ac.dtb': [bcm4708_smartrg_sr400ac],
              'armada-370-db.dtb': [armada_370_db],
              'armada-370-mirabox.dtb': [armada_370_mirabox],
              'orion5x-rd88f5182-nas.dtb': [orion5x_rd88f5182_nas],
              'armada-370-rd.dtb': [armada_370_rd],
              'armada-375-db.dtb': [armada_375_db],
              'armada-385-db-ap.dtb': [armada_385_db_ap],
              'armada-388-gp.dtb': [armada_388_gp],
              'armada-398-db.dtb': [armada_398_db],
              'kirkwood-db-88f6282.dtb': [kirkwood_db_88f6282],
              'armada-3720-db.dtb': [armada_3720_db],
              'armada-7040-db.dtb': [armada_7040_db],
              'armada-xp-db.dtb': [armada_xp_db],
              'armada-xp-gp.dtb': [armada_xp_gp],
              'exynos5250-arndale.dtb': [arndale],
              'exynos5250-snow.dtb': [snow],
              'exynos5420-arndale-octa.dtb': [arndale_octa],
              'exynos5800-peach-pi.dtb': [peach_pi],
              'exynos5422-odroidxu3.dtb': [odroid_xu3],
              'exynos4412-odroidu3.dtb': [odroid_u2],
              'exynos4412-odroidx2.dtb': [odroid_x2],
              'am335x-boneblack.dtb': [beaglebone_black],
              'omap3-beagle-xm.dtb': [beagle_xm],
              'omap3-overo-tobi.dtb': [omap3_overo_tobi],
              'omap3-overo-storm-tobi.dtb': [omap3_overo_storm_tobi],
              'omap4-panda-es.dtb': [panda_es],
              'omap4-panda.dtb': [panda],
              'omap5-uevm.dtb' : [omap5_uevm],
              'sun7i-a20-cubieboard2.dtb': [cubieboard2],
              'sun7i-a20-cubietruck.dtb': [cubieboard3, cubieboard3_kvm],
              'sun7i-a20-bananapi.dtb': [sun7i_a20_bananapi],
              'hip04-d01.dtb': [d01],
              'hisi-x5hd2-dkb.dtb': [hisi_x5hd2_dkb],
              'imx6q-wandboard.dtb': [imx6q_wandboard],
              'imx6q-sabrelite.dtb': [imx6q_sabrelite],
              'imx6q-cm-fx6.dtb': [utilite_pro],
              'meson8b-odroidc1.dtb': [meson8b_odroidc1],
              'da850-lcdk.dtb': [da850_lcdk],
              'ste-snowball.dtb': [snowball],
              'qcom-apq8084-ifc6540.dtb': [ifc6540],
              'qcom-apq8064-ifc6410.dtb': [ifc6410],
              'highbank.dtb': [highbank],
              'at91-sama5d3_xplained.dtb': [sama53d],
              'tegra124-jetson-tk1.dtb': [jetson_tk1],
              'tegra124-nyan-big.dtb': [tegra124_nyan_big],
              'zynq-parallella.dtb': [parallella],
              'zynq-zc702.dtb': [zynq_zc702],
              'sun9i-a80-optimus.dtb': [optimus_a80],
              'sun9i-a80-cubieboard4.dtb': [cubieboard4],
              'rk3288-rock2-square.dtb': [rk3288_rock2_square],
#              'zx296702-ad1.dtb': [zx296702_ad1],
              'vexpress-v2p-ca15-tc1.dtb': [qemu_arm_cortex_a15],
              'vexpress-v2p-ca15-tc1-legacy': [qemu_arm_cortex_a15_legacy],
              'vexpress-v2p-ca15_a7.dtb': [qemu_arm_cortex_a15_a7],
              'vexpress-v2p-ca9.dtb': [qemu_arm_cortex_a9],
              'vexpress-v2p-ca9-legacy': [qemu_arm_cortex_a9_legacy],
              'qemu-aarch64-legacy': [qemu_aarch64],
              'apq8016-sbc.dtb': [apq8016_sbc],
              'apm-mustang.dtb': [apm_mustang, apm_mustang_kvm],
              'juno.dtb': [juno, juno_kvm],
              'fvp-base-gicv2-psci.dtb': [fvp_aemv8a],
              'hi6220-hikey.dtb': [hi6220_hikey],
              'fsl-ls2080a-simu.dtb': [fsl_ls2080a_simu],
              'fsl-ls2080a-rdb.dtb': [fsl_ls2080a_rdb],
              'x86': [x86, minnowboard_max_E3825, x86_atom330],
              'x86-kvm': [x86_kvm],
              'qemu-i386': [qemu_i386],
              'imx6dl-riotboard.dtb': [imx6dl_riotboard],
              'imx53-qsrb.dtb': [imx53_qsbr],
              'imx28-duckbill.dtb': [imx28_duckbill],
              'imx23-olinuxino.dtb': [imx23_olinuxino],
              'socfpga_cyclone5_socrates.dtb': [socfpga_cyclone5_socrates],
              'imx27-phytec-phycard-s-rdk.dtb': [imx27_phycard_s],
              'armada-xp-linksys-mamba.dtb': [armada_xp_linksys_mamba],
              'armada-388-clearfog.dtb': [armada_388_clearfog],
              'sun5i-r8-chip.dtb': [chip],
              'imx6q-nitrogen6x.dtb': [imx6q_nitrogen6x],
              'sama5d34ek.dtb': [sama5d34ek],
              'sama5d36ek.dtb': [sama5d36ek],
              'sama5d35ek.dtb': [sama5d35ek],
              'at91sam9261ek.dtb': [sam9261ek],
              'at91sam9x25ek.dtb': [sam9x25ek],
              'at91sam9x35ek.dtb': [at91sam9x35ek],
              'at91rm9200ek.dtb': [at91rm9200ek],
              'at91-sama5d2_xplained.dtb': [at91_sama5d2_xplained],
              'at91-sama5d4_xplained.dtb': [at91_sama5d4_xplained],
              'at91sam9m10g45ek.dtb': [at91sam9m10g45ek],
              'sun8i-a83t-allwinner-h8homlet-v2.dtb': [sun8i_a83t_allwinner_h8homlet_v2],
              'sun8i-a33-sinlinx-sina33.dtb': [sinlinx_sina33],
              'kirkwood-openblocks_a7.dtb': [openblocks_a7],
              'armada-xp-openblocks-ax3-4.dtb': [openblocks_ax3],
              'vf610-zii-dev-rev-b.dtb': [vf610_zii_dev_rev_b]}
