# Copyright (C) 2016, 2017 Linaro Limited
# Author: Matt Hart <matthew.hart@linaro.org>
# Author: Tyler Baker <tyler.baker@linaro.org>
#
# Copyright (C) 2016, 2017 Baylibre SAS
# Author: Jerome Brunet <jbrunet@baylibre.com>
# Author: Kevin Hilman <khilman@baylibre.com>
#
# Copyright (C) 2016, 2017 Free Electrons
# Author: Alexandre Belloni <alexandre.belloni@free-electrons.com>
# Author: Florent Jacquet <florent.jacquet@free-electrons.com>
# Author: Quentin Schulz <quentin.schulz@free-electrons.com>
#
# Copyright (C) 2016, 2017 Pengutronix
# Author: Michael Grzeschik <m.grzeschik@pengutronix.de>
#
# Copyright (C) 2017, 2018 Collabora Limited
# Author: Tomeu Vizoso <tomeu.vizoso@collabora.com>
# Author: Guillaume Tucker <guillaume.tucker@collabora.com>
#
# This module is free software; you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; either version 2.1 of the License, or (at your option)
# any later version.
#
# This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this library; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

alpine_db = {'device_type': 'alpine-db',
                      'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                      'kernel_defconfig_blacklist': [],
                      'defconfig_blacklist': ['allmodconfig'],
                      'kernel_blacklist': [],
                      'nfs_blacklist': [],
                      'lpae': False,
                      'fastboot': False,
                      'mach': 'alpine'}

alpine_v2_evp = {'device_type': 'alpine-v2-evp',
                      'templates': ['generic-arm64-dtb-kernel-ci-boot-template.json'],
                      'kernel_defconfig_blacklist': [],
                      'defconfig_blacklist': ['allmodconfig'],
                      'kernel_blacklist': [],
                      'nfs_blacklist': [],
                      'lpae': False,
                      'fastboot': False,
                      'mach': 'alpine'}

bcm2835_rpi_b_plus = {'device_type': 'bcm2835-rpi-b-plus',
                      'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                      'kernel_defconfig_blacklist': [],
                      'defconfig_blacklist': ['allmodconfig'],
                      'kernel_blacklist': [],
                      'nfs_blacklist': [],
                      'lpae': False,
                      'fastboot': False,
                      'mach': 'bcm'}

bcm2836_rpi_2_b = {'device_type': 'bcm2836-rpi-2-b',
                      'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                      'kernel_defconfig_blacklist': [],
                      'defconfig_blacklist': ['allmodconfig'],
                      'kernel_blacklist': [],
                      'nfs_blacklist': [],
                      'lpae': False,
                      'fastboot': False,
                      'mach': 'bcm'}

bcm2837_rpi_3_b = {'device_type': 'bcm2837-rpi-3-b',
               'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                             'generic-uboot-tftp-ramdisk-kselftest-template.jinja2',
                             'generic-uboot-tftp-ramdisk-simple-template.jinja2'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['allnoconfig',
                                       'allmodconfig'],
               'arch_blacklist': ['arm'],
               'kernel_blacklist': ['v4.13-', 'v4.13.', 'v4.14-rc1', 'v4.14-rc5', 'for-4.15', 'v3.', '4.4-', '4.9-'],
               'nfs_blacklist': [],
               'lpae': False,
               'fastboot': False,
               'context': {'console_device': 'ttyS1', 'test_character_delay': 10},
               'mach': 'bcm'}

bcm2837_rpi_3_b_32 = {'device_type': 'bcm2837-rpi-3-b-32',
               'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                             'generic-uboot-tftp-ramdisk-kselftest-template.jinja2',
                             'generic-uboot-tftp-ramdisk-simple-template.jinja2'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['allnoconfig',
                                       'allmodconfig'],
               'defconfig_whitelist': ['bcm2835_defconfig'],
               'arch_blacklist': ['arm64'],
               'kernel_blacklist': ['v4.13-', 'v4.13.', 'v4.14-rc1', 'v4.14-rc5', 'for-4.15', 'v3.', '4.4-', '4.9-'],
               'nfs_blacklist': [],
               'lpae': False,
               'fastboot': False,
               'context': {'console_device': 'ttyS1', 'test_character_delay': 10},
               'mach': 'bcm'}

bcm4708_smartrg_sr400ac = {'device_type': 'bcm4708-smartrg-sr400ac',
                           'templates': ['cfe-arm-dtb-kernel-ci-boot-template.json',
                                         'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                           'kernel_defconfig_blacklist': [],
                           'defconfig_blacklist': ['allmodconfig',
                                                   'multi_v7_defconfig+CONFIG_PROVE_LOCKING=y'],
                           'kernel_blacklist': ['v3.18',
                                                'v4.1',
                                                'v4.2',
                                                'lsk-v3.18',
                                                'lsk-v4.1',
                                                'stable-queue-v4.2'],
                           'nfs_blacklist': [],
                           'lpae': False,
                           'fastboot': False,
                           'mach': 'bcm'}

armada_370_db = {'device_type': 'armada-370-db',
                       'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['allmodconfig'],
                       'kernel_blacklist': ['v3'],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False,
                       'mach': 'mvebu'}

armada_370_mirabox = {'device_type': 'armada-370-mirabox',
                       'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                     'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False,
                       'mach': 'mvebu'}

orion5x_rd88f5182_nas = {'device_type': 'orion5x-rd88f5182-nas',
                       'templates': ['generic-uboot-tftp-nfs-template.jinja2'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False,
                       'mach': 'mvebu'}

armada_370_rd = {'device_type': 'armada-370-rd',
                       'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
		       'kernel_defconfig_blacklist': [{'kernel_version': 'v4.0', 'defconfig': 'multi_v7_defconfig'},
						      {'kernel_version': 'v4.1', 'defconfig': 'multi_v7_defconfig'},
						      {'kernel_version': 'v4.2', 'defconfig': 'multi_v7_defconfig'},
						      {'kernel_version': 'v4.3', 'defconfig': 'multi_v7_defconfig'}],
                       'defconfig_blacklist': ['allmodconfig'],
                       'kernel_blacklist': ['v3'],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False,
                       'mach': 'mvebu'}

armada_375_db = {'device_type': 'armada-375-db',
                       'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False,
                       'mach': 'mvebu'}

armada_385_db_ap = {'device_type': 'armada-385-db-ap',
                       'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False,
                       'mach': 'mvebu'}

armada_388_gp = {'device_type': 'armada-388-gp',
                       'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False,
                       'mach': 'mvebu'}

armada_398_db = {'device_type': 'armada-398-db',
                       'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False,
                       'mach': 'mvebu'}

kirkwood_db_88f6282 = {'device_type': 'kirkwood-db-88f6282',
                       'templates': ['generic-uboot-tftp-nfs-template.jinja2'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['allmodconfig',
			# To be removed once NFS is working for this defconfig
					       'multi_v5_defconfig'],
                       'kernel_blacklist': ['v3'],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False,
                       'mach': 'mvebu'}

armada_3720_db = {'device_type': 'armada-3720-db',
                       'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False,
                       'mach': 'mvebu'}

armada_7040_db = {'device_type': 'armada-7040-db',
                       'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['allmodconfig'],
                       'kernel_blacklist': ['v4.6'],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False,
                       'mach': 'mvebu'}

armada_8040_db = {'device_type': 'armada-8040-db',
                       'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False,
                       'mach': 'mvebu'}

armada_xp_db = {'device_type': 'armada-xp-db',
                       'templates': ['generic-uboot-tftp-nfs-template.jinja2'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False,
                       'mach': 'mvebu'}

armada_xp_gp = {'device_type': 'armada-xp-gp',
                       'templates': ['generic-uboot-tftp-nfs-template.jinja2'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False,
                       'mach': 'mvebu'}

arndale = {'device_type': 'arndale',
           'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                         'generic-uboot-tftp-ramdisk-kselftest-template.jinja2'],
           'kernel_defconfig_blacklist': [],
           'defconfig_blacklist': ['allmodconfig',
                                   'multi_v7_defconfig+CONFIG_SMP=n'],
           'kernel_blacklist': [],
           'nfs_blacklist': [],
           'lpae': True,
           'fastboot': False,
           'mach': 'exynos'}

snow = {'device_type': 'snow',
        'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                      'generic-uboot-tftp-ramdisk-kselftest-template.jinja2',
                      'generic-uboot-tftp-nfs-template.jinja2'],
        'kernel_defconfig_blacklist': [],
        'defconfig_blacklist': ['allmodconfig',
                                'multi_v7_defconfig+CONFIG_SMP=n'],
        'kernel_blacklist': [],
        'nfs_blacklist': [],
        'lpae': True,
        'fastboot': False,
        'mach': 'exynos'}

arndale_octa = {'device_type': 'arndale-octa',
                'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                              'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                              'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                              'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                'kernel_defconfig_blacklist': [],
                'defconfig_blacklist': ['allmodconfig',
                                        'multi_v7_defconfig+linaro-base+distribution'],
                'kernel_blacklist': [],
                'nfs_blacklist': ['v3.',
                                  'lsk-v3.'],
                'lpae': True,
                'fastboot': False,
                'mach': 'exynos'}

peach_pi = {'device_type': 'peach-pi',
            'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                          'generic-uboot-tftp-ramdisk-kselftest-template.jinja2'],
            'kernel_defconfig_blacklist': [],
            'defconfig_blacklist': ['allmodconfig'],
            'kernel_blacklist': [],
            'nfs_blacklist': ['v3.',
                              'lsk-v3.'],
            'lpae': True,
            'fastboot': False,
            'mach': 'exynos'}

odroid_xu3 = {'device_type': 'odroid-xu3',
              'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                            'generic-uboot-tftp-ramdisk-kselftest-template.jinja2',
                            'generic-uboot-tftp-nfs-template.jinja2'],
              'kernel_defconfig_blacklist': [],
              'defconfig_blacklist': ['allmodconfig'],
              'kernel_blacklist': [],
              'nfs_blacklist': [],
              'lpae': True,
              'fastboot': False,
              'mach': 'exynos'}

odroid_u2 = {'device_type': 'odroid-u2',
             'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                           'generic-arm-dtb-kernel-ci-kselftest-template.json'],
             'kernel_defconfig_blacklist': [],
             'defconfig_blacklist': ['allmodconfig',
                                     'multi_v7_defconfig+CONFIG_THUMB2_KERNEL=y',
                                     'multi_v7_defconfig+linaro-base+distribution'],
             'kernel_blacklist': [],
             'nfs_blacklist': [],
             'lpae': False,
             'fastboot': False,
             'mach': 'exynos'}

odroid_x2 = {'device_type': 'odroid-x2',
             'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                           'generic-uboot-tftp-ramdisk-kselftest-template.jinja2',
                           'generic-uboot-tftp-nfs-template.jinja2'],
             'kernel_defconfig_blacklist': [],
             'defconfig_blacklist': ['allmodconfig'],
             'kernel_blacklist': [],
             'nfs_blacklist': [],
             'lpae': False,
             'fastboot': False,
             'mach': 'exynos'}

beaglebone_black = {'device_type': 'beaglebone-black',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                                  'generic-uboot-tftp-nfs-template.jinja2',
                                  'generic-uboot-tftp-ramdisk-kselftest-template.jinja2',
                                  'generic-uboot-tftp-ramdisk-simple-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lab_blacklist': ['lab-baylibre'],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'omap2'}

beagle_xm = {'device_type': 'beagle-xm',
             'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                           'generic-uboot-tftp-ramdisk-kselftest-template.jinja2'],
             'kernel_defconfig_blacklist': [],
             'defconfig_blacklist': ['allmodconfig'],
             'kernel_blacklist': ['v3.14',
                                  'lsk-v3.14'],
             'nfs_blacklist': [],
             'lpae': False,
             'fastboot': False,
             'mach': 'omap2'}

omap3_overo_tobi = {'device_type': 'omap3-overo-tobi',
                    'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                  'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'omap2'}

omap3_overo_storm_tobi = {'device_type': 'omap3-overo-storm-tobi',
                          'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                        'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                          'kernel_defconfig_blacklist': [],
                          'defconfig_blacklist': ['allmodconfig'],
                          'kernel_blacklist': [],
                          'nfs_blacklist': [],
                          'lpae': False,
                          'fastboot': False,
                          'mach': 'omap2'}

panda_es = {'device_type': 'panda-es',
            'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                          'generic-uboot-tftp-ramdisk-kselftest-template.jinja2'],
            'kernel_defconfig_blacklist': [],
            'defconfig_blacklist': ['allmodconfig'],
            'kernel_blacklist': [],
            'nfs_blacklist': [],
            'lpae': False,
            'fastboot': False,
            'mach': 'omap2'}

panda = {'device_type': 'panda',
         'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                       'generic-uboot-tftp-ramdisk-kselftest-template.jinja2'],
         'kernel_defconfig_blacklist': [],
         'defconfig_blacklist': ['allmodconfig',
                                 'multi_v7_defconfig+CONFIG_PROVE_LOCKING=y',
                                 'multi_v7_defconfig+kselftest'],
         'kernel_blacklist': [],
         'nfs_blacklist': [],
         'lpae': False,
         'fastboot': False,
         'mach': 'omap2'}

omap5_uevm = {'device_type': 'omap5-uevm',
              'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                            'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                            'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                            'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                            'generic-arm-dtb-kernel-ci-kselftest-template.json'],
              'kernel_defconfig_blacklist': [],
              'defconfig_blacklist': ['allmodconfig'],
              'kernel_blacklist': [],
              'nfs_blacklist': [],
              'lpae': True,
              'fastboot': False,
              'mach': 'omap2'}

dra7_evm = {'device_type': 'dra7-evm',
            'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                          'generic-uboot-tftp-ramdisk-kselftest-template.jinja2',
                          'generic-uboot-tftp-ramdisk-simple-template.jinja2'],
            'kernel_defconfig_blacklist': [],
            'defconfig_blacklist': ['allmodconfig'],
            'kernel_blacklist': [],
            'nfs_blacklist': [],
            'lpae': False,
            'fastboot': False,
            'mach': 'omap2'}

cubieboard2 = {'device_type': 'cubieboard2',
               'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                             'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                             'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                             'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                             'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                             'generic-arm-dtb-kernel-ci-cpufreq-ljt-stress-test-template.json',
                             'generic-arm-dtb-kernel-ci-kselftest-template.json'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': ['v3.10',
                                 'lsk-v3.10',
                                 'v3.14',
                                 'lsk-v3.14',
                                 'v4.5'],
               'lpae': True,
               'be': False,
               'fastboot': False,
               'mach': 'sunxi'}

cubieboard3 = {'device_type': 'cubieboard3',
               'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                             'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                             'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                             'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                             'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                             'generic-arm-dtb-kernel-ci-cpufreq-ljt-stress-test-template.json',
                             'generic-arm-dtb-kernel-ci-kselftest-template.json',
                             'generic-arm-dtb-kernel-ci-hackbench-template.json'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': ['v3.10',
                                 'lsk-v3.10',
                                 'v3.14',
                                 'lsk-v3.14'],
               'lpae': True,
               'be': False,
               'fastboot': False,
               'mach': 'sunxi'}

cubieboard3_kvm = {'device_type': 'cubieboard3',
                   'templates': ['generic-arm-boot-kvm-template.json'],
                   'kernel_defconfig_blacklist': [],
                   'defconfig_blacklist': [],
                   'kernel_blacklist': [],
                   'nfs_blacklist': [],
                   'lpae': True,
                   'fastboot': False,
                   'mach': 'sunxi'}

sun7i_a20_bananapi = {'device_type': 'sun7i-a20-bananapi',
                      'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                    'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                                    'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                                    'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                                    'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                                    'generic-arm-dtb-kernel-ci-cpufreq-ljt-stress-test-template.json',
                                    'generic-arm-dtb-kernel-ci-kselftest-template.json',
                                    'generic-arm-dtb-kernel-ci-hackbench-template.json'],
                      'kernel_defconfig_blacklist': [],
                      'defconfig_blacklist': ['allmodconfig'],
                      'kernel_blacklist': [],
                      'nfs_blacklist': [],
                      'lpae': True,
                      'be': False,
                      'fastboot': False,
                      'mach': 'sunxi'}

hisi_x5hd2_dkb = {'device_type': 'hi3716cv200',
                  'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                                'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                                'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                                'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                                'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                  'kernel_defconfig_blacklist': [],
                  'defconfig_blacklist': ['allmodconfig'],
                  'kernel_blacklist': [],
                  'nfs_blacklist': ['v3.',
                                    'lsk-v3.'],
                  'lpae': False,
                  'fastboot': False,
                  'mach': 'hisi'}

d01 = {'device_type': 'd01',
       'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                     'generic-arm-dtb-kernel-ci-kselftest-template.json'],
       'kernel_defconfig_blacklist': [],
       'defconfig_blacklist': ['allmodconfig',
                               'multi_v7_defconfig+linaro-base+distribution'],
       'kernel_blacklist': [],
       'nfs_blacklist': [],
       'lpae': True,
       'fastboot': False,
       'mach': 'hisi'}

d03 = {'device_type': 'd03',
       'templates': ['generic-grub-tftp-ramdisk-template.jinja2'],
       'kernel_defconfig_blacklist': [],
        'defconfig_blacklist': ['allnoconfig',
                                'allmodconfig'],
       'kernel_blacklist': [],
       'nfs_blacklist': [],
       'lpae': True,
       'fastboot': False,
       'mach': 'hisi'}

d05 = {'device_type': 'hip07-d05',
       'templates': ['generic-grub-tftp-ramdisk-template.jinja2',
                     'generic-grub-tftp-nfs-template.jinja2'],
       'kernel_defconfig_blacklist': [],
       'defconfig_blacklist': ['allnoconfig',
                               'allmodconfig'],
       'kernel_blacklist': [],
       'nfs_blacklist': [],
       'lpae': True,
       'fastboot': False,
       'mach': 'hisi'}

imx6ul_pico_hobbit = {'device_type': 'imx6ul-pico-hobbit',
                   'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                 'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                                 'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                                 'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                                 'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                                 'generic-arm-dtb-kernel-ci-kselftest-template.json',
                                 'generic-arm-dtb-kernel-ci-hackbench-template.json'],
                   'kernel_defconfig_blacklist': [],
                   'defconfig_blacklist': ['imx_v4_v5_defconfig',
                                           'multi_v5_defconfig',
                                           'allmodconfig'],
                   'kernel_blacklist': [],
                   'nfs_blacklist': [],
                   'lpae': False,
                   'fastboot': False,
                   'mach': 'imx'}

imx6q_wandboard = {'device_type': 'imx6q-wandboard',
                   'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                 'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                                 'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                                 'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                                 'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                                 'generic-arm-dtb-kernel-ci-kselftest-template.json',
                                 'generic-arm-dtb-kernel-ci-hackbench-template.json'],
                   'kernel_defconfig_blacklist': [],
                   'defconfig_blacklist': ['imx_v4_v5_defconfig',
                                           'multi_v5_defconfig',
                                           'allmodconfig'],
                   'kernel_blacklist': [],
                   'nfs_blacklist': [],
                   'lpae': False,
                   'fastboot': False,
                   'mach': 'imx'}

imx6q_sabrelite = {'device_type': 'imx6q-sabrelite',
                   'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                                 'generic-uboot-tftp-ramdisk-kselftest-template.jinja2',
                                 'generic-uboot-tftp-nfs-template.jinja2'],
                   'kernel_defconfig_blacklist': [],
                   'defconfig_blacklist': ['imx_v4_v5_defconfig',
                                           'imx_v6_v7_defconfig',
                                           'multi_v5_defconfig',
                                           'allmodconfig',
                                           'multi_v7_defconfig+kselftest'],
                   'kernel_blacklist': ['v3.18',
                                        'lsk-v3.18'],
                   'nfs_blacklist': [],
                   'lpae': False,
                   'fastboot': False,
                   'mach': 'imx'}

utilite_pro = {'device_type': 'utilite-pro',
               'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                             'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                             'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                             'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                             'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                             'generic-arm-dtb-kernel-ci-kselftest-template.json',
                             'generic-arm-dtb-kernel-ci-hackbench-template.json'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['imx_v4_v5_defconfig',
                                       'multi_v5_defconfig',
                                       'allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': [],
               'lpae': False,
               'fastboot': False,
               'mach': 'imx'}

meson8b_odroidc1 = {'device_type': 'meson8b-odroidc1',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                                  'generic-uboot-tftp-ramdisk-kselftest-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'meson'}

meson_gxbb_odroidc2 = {'device_type': 'meson-gxbb-odroidc2',
               'templates': ['generic-arm64-dtb-kernel-ci-boot-template.json',
                             'generic-arm64-dtb-kernel-ci-boot-be-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-cyclictest-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-hackbench-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-lmbench-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-ltp-realtime-template.json',
                             'generic-arm64-dtb-kernel-ci-kselftest-template.json'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['allnoconfig',
                                       'allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': [],
               'lpae': False,
               'fastboot': True,
               'mach': 'amlogic',
               'boot_be': True}

meson_gxbb_p200 = {'device_type': 'meson-gxbb-p200',
               'templates': ['generic-arm64-dtb-kernel-ci-boot-template.json',
                             'generic-arm64-dtb-kernel-ci-boot-be-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-cyclictest-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-hackbench-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-lmbench-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-ltp-realtime-template.json',
                             'generic-arm64-dtb-kernel-ci-kselftest-template.json'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['allnoconfig',
                                       'allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': [],
               'lpae': False,
               'fastboot': True,
               'mach': 'amlogic',
               'boot_be': True}

meson_gxl_s905x_khadas_vim  = {'device_type': 'meson-gxl-s905x-khadas-vim',
               'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                             'generic-uboot-tftp-ramdisk-kselftest-template.jinja2',
                             'generic-uboot-tftp-ramdisk-boot-be-template.jinja2',
                             'generic-uboot-tftp-ramdisk-simple-template.jinja2'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['allnoconfig',
                                       'allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': [],
               'lpae': False,
               'fastboot': False,
               'mach': 'amlogic',
               'boot_be': True}


r8a7795_salvator_x = {'device_type': 'r8a7795-salvator-x',
               'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                             'generic-uboot-tftp-ramdisk-boot-be-template.jinja2',
                             'generic-uboot-tftp-nfs-template.jinja2'
                             'generic-uboot-tftp-ramdisk-kselftest-template.jinja2',
                             'generic-uboot-tftp-ramdisk-simple-template.jinja2'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['allnoconfig',
                                       'allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': [],
               'lpae': False,
               'fastboot': False,
               'mach': 'renesas',
               'boot_be': True}

r8a7796_m3ulcb = {'device_type': 'r8a7796-m3ulcb',
               'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                             'generic-uboot-tftp-ramdisk-simple-template.jinja2'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['allnoconfig',
                                       'allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': [],
               'lpae': False,
               'fastboot': False,
               'mach': 'renesas'}

r8a7791_porter = {'device_type': 'r8a7791-porter',
               'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': [],
               'lpae': False,
               'fastboot': False,
               'mach': 'renesas'}


da850_lcdk = {'device_type': 'da850-lcdk',
                    'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                  'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                                  'generic-arm-dtb-kernel-ci-kselftest-template.json',
                                  'generic-arm-dtb-kernel-ci-hackbench-template.json'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'davinci'}

snowball = {'device_type': 'snowball',
            'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                          'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                          'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                          'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                          'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                          'generic-arm-dtb-kernel-ci-kselftest-template.json',
                          'generic-arm-dtb-kernel-ci-hackbench-template.json'],
            'kernel_defconfig_blacklist': [],
            'defconfig_blacklist': ['allmodconfig'],
            'kernel_blacklist': [],
            'nfs_blacklist': [],
            'lpae': False,
            'fastboot': False,
            'mach': 'u8500'}

ifc6540 = {'device_type': 'ifc6540',
           'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                         'generic-arm-dtb-kernel-ci-kselftest-template.json',
                         'generic-arm-dtb-kernel-ci-hackbench-template.json'],
           'kernel_defconfig_blacklist': [],
           'defconfig_blacklist': ['allmodconfig'],
           'kernel_blacklist': [],
           'nfs_blacklist': [],
           'lpae': False,
           'fastboot': True,
           'mach': 'qcom'}

ifc6410 = {'device_type': 'ifc6410',
           'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                         'generic-arm-dtb-kernel-ci-kselftest-template.json',
                         'generic-arm-dtb-kernel-ci-hackbench-template.json'],
           'kernel_defconfig_blacklist': [],
           'defconfig_blacklist': ['allmodconfig'],
           'kernel_blacklist': [],
           'nfs_blacklist': [],
           'lpae': False,
           'fastboot': True,
           'mach': 'qcom'}

highbank = {'device_type': 'highbank',
            'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                          'generic-arm-dtb-kernel-ci-kselftest-template.json',
                          'generic-arm-dtb-kernel-ci-hackbench-template.json'],
            'kernel_defconfig_blacklist': [],
            'defconfig_blacklist': ['allmodconfig',
                                    'arm-multi_v7_defconfig+CONFIG_SMP=n'],
            'kernel_blacklist': [],
            'nfs_blacklist': [],
            'lpae': False,
            'fastboot': True,
            'mach': 'highbank'}

sama53d = {'device_type': 'sama53d',
           'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                         'generic-uboot-tftp-nfs-template.jinja2',
                         'generic-uboot-tftp-ramdisk-kselftest-template.jinja2'],
           'kernel_defconfig_blacklist': [],
           'defconfig_blacklist': ['at91_dt_defconfig',
                                   'at91sam9260_9g20_defconfig',
                                   'at91sam9g45_defconfig',
                                   'allmodconfig'],
           'kernel_blacklist': [],
           'nfs_blacklist': [],
           'lpae': False,
           'fastboot': False,
           'mach': 'at91'}

jetson_tk1 = {'device_type': 'jetson-tk1',
              'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                            'generic-uboot-tftp-nfs-template.jinja2',
                            'generic-uboot-tftp-ramdisk-kselftest-template.jinja2'],
              'kernel_defconfig_blacklist': [],
              'defconfig_blacklist': ['allmodconfig',
                                      'multi_v7_defconfig+kselftest'],
              'kernel_blacklist': [],
              'nfs_blacklist': [],
              'lpae': True,
              'fastboot': False,
              'mach': 'tegra'}

tegra124_nyan_big = {'device_type': 'tegra124-nyan-big',
                     'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                                   'generic-uboot-tftp-ramdisk-kselftest-template.jinja2'],
                     'kernel_defconfig_blacklist': [],
                     'defconfig_blacklist': ['allmodconfig'],
                     'kernel_blacklist': [],
                     'nfs_blacklist': [],
                     'lpae': True,
                     'fastboot': False,
                     'mach': 'tegra'}

parallella = {'device_type': 'parallella',
              'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                            'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                            'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                            'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                            'generic-arm-dtb-kernel-ci-kselftest-template.json'],
              'kernel_defconfig_blacklist': [],
              'defconfig_blacklist': ['allmodconfig',
                                      'multi_v7_defconfig+linaro-base+distribution'],
              'kernel_blacklist': [],
              'nfs_blacklist': [],
              'lpae': False,
              'fastboot': False,
              'mach': 'zynq'}

zynq_zc702 = {'device_type': 'zynq-zc702',
              'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
              'kernel_defconfig_blacklist': [],
              'defconfig_blacklist': ['allmodconfig',
                                      'multi_v7_defconfig+linaro-base+distribution'],
              'kernel_blacklist': [],
              'nfs_blacklist': [],
              'lpae': False,
              'fastboot': False,
              'mach': 'zynq'}

optimus_a80 = {'device_type': 'optimus-a80',
               'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                             'generic-arm-dtb-kernel-ci-kselftest-template.json'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': [],
               'lpae': True,
               'fastboot': True,
               'mach': 'sunxi'}

cubieboard4 = {'device_type': 'cubieboard4',
               'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                             'generic-arm-dtb-kernel-ci-kselftest-template.json'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': [],
               'lpae': True,
               'fastboot': True,
               'mach': 'sunxi'}

rk3288_rock2_square = {'device_type': 'rk3288-rock2-square',
                       'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                                     'generic-uboot-tftp-ramdisk-kselftest-template.jinja2',
                                     'generic-uboot-tftp-nfs-template.jinja2'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': True,
                       'fastboot': True,
                       'mach': 'rockchip'}

rk3288_veyron_jaq = {'device_type': 'rk3288-veyron-jaq',
                     'templates': ['generic-depthcharge-tftp-ramdisk-template.jinja2',
                                   'generic-depthcharge-tftp-nfs-template.jinja2',
                                   'generic-depthcharge-tftp-ramdisk-sleep-template.jinja2'],
                     'kernel_defconfig_blacklist': [],
                     'defconfig_blacklist': ['allmodconfig'],
                     'kernel_blacklist': [],
                     'nfs_blacklist': [],
                     'lpae': True,
                     'fastboot': False,
                     'mach': 'rockchip'}

rk3399_gru_kevin = {'device_type': 'rk3399-gru-kevin',
                    'templates': ['generic-depthcharge-tftp-ramdisk-template.jinja2',
                                  'generic-depthcharge-tftp-nfs-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': True,
                    'fastboot': False,
                    'mach': 'rockchip'}

rk3399_puma_haikou = {'device_type': 'rk3399-puma-haikou',
               'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                             'generic-uboot-tftp-ramdisk-kselftest-template.jinja2'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['allmodconfig'],
               'arch_blacklist': ['arm'],
               'kernel_blacklist': ['v3.', 'v4.1.', 'v4.2.', 'v4.3.', 'v4.4.', 'v4.5.', '4.6.', '4.7.',
                                    'v4.8.', 'v4.9.', 'v4.10.', 'v4.11.', 'v4.12.', 'v4.13.'],
               'nfs_blacklist': [],
               'lpae': False,
               'fastboot': False,
               'mach': 'rockchip'}

zx296702_ad1 = {'device_type': 'zx296702-ad1',
                'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                              'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                'kernel_defconfig_blacklist': [],
                'defconfig_blacklist': ['allmodconfig'],
                'kernel_blacklist': [],
                'nfs_blacklist': [],
                'lpae': False,
                'fastboot': True,
                'mach': 'sunxi'}

vf610_zii_dev_rev_b = {'device_type': 'vf610-zii-dev-rev-b',
                       'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                     'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                                     'generic-arm-dtb-kernel-ci-kselftest-template.json',
                                     'generic-arm-dtb-kernel-ci-hackbench-template.json'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': True,
                       'mach': 'imx'}

qemu_arm_cortex_a9 = {'device_type': 'qemu-arm-cortex-a9',
                      'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                    'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                      'kernel_defconfig_blacklist': [],
                      'defconfig_blacklist': ['allmodconfig',
                                              'multi_v7_defconfig+CONFIG_PROVE_LOCKING=y'],
                      'kernel_blacklist': [],
                      'nfs_blacklist': [],
                      'lpae': False,
                      'fastboot': False,
                      'mach': 'vexpress'}

qemu_arm_cortex_a9_legacy = {'device_type': 'qemu-arm-cortex-a9',
                             'templates': ['generic-arm-kernel-ci-boot-template.json',
                                           'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                             'kernel_defconfig_blacklist': [],
                             'defconfig_blacklist': ['allmodconfig',
                                                     'multi_v7_defconfig+CONFIG_PROVE_LOCKING=y'],
                             'kernel_blacklist': [],
                             'nfs_blacklist': [],
                             'lpae': False,
                             'fastboot': False,
                             'mach': 'vexpress'}

qemu_arm_cortex_a15_a7 = {'device_type': 'qemu-arm-cortex-a15',
                          'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                        'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                          'kernel_defconfig_blacklist': [],
                          'defconfig_blacklist': ['allmodconfig',
                                                  'multi_v7_defconfig+CONFIG_PROVE_LOCKING=y',
                                                  'multi_v7_defconfig+kselftest'],
                          'kernel_blacklist': [],
                          'nfs_blacklist': [],
                          'lpae': True,
                          'fastboot': False,
                          'mach': 'vexpress'}

qemu_arm_cortex_a15 = {'device_type': 'qemu-arm-cortex-a15',
                       'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                     'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['allmodconfig',
                                               'multi_v7_defconfig+CONFIG_PROVE_LOCKING=y'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': True,
                       'fastboot': False,
                       'mach': 'vexpress'}

qemu_arm_cortex_a15_legacy = {'device_type': 'qemu-arm-cortex-a15',
                              'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                            'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                              'kernel_defconfig_blacklist': [],
                              'defconfig_blacklist': ['allmodconfig',
                                                      'multi_v7_defconfig+CONFIG_PROVE_LOCKING=y'],
                              'kernel_blacklist': [],
                              'nfs_blacklist': [],
                              'lpae': True,
                              'fastboot': False,
                              'mach': 'vexpress'}

qemu = {'device_type': 'qemu',
        'templates': ['qemu-generic-boot-template.jinja2'],
        'kernel_defconfig_blacklist': [],
        'defconfig_whitelist': ['defconfig',
                                'x86_64_defconfig',
                                'vexpress_defconfig',
                                'multi_v7_defconfig'],
        'defconfig_blacklist': [],
        'kernel_blacklist': [],
        'nfs_blacklist': [],
        'lpae': False,
        'fastboot': False,
        'mach': 'qemu'}

qemu_aarch64 = {'device_type': 'qemu-aarch64',
                'templates': ['generic-arm64-kernel-ci-boot-template.json',
                              'generic-arm64-kernel-ci-kselftest-template.json'],
                'kernel_defconfig_blacklist': [],
                'defconfig_blacklist': ['allnoconfig',
                                        'allmodconfig',
                                        'defconfig+CONFIG_PROVE_LOCKING=y'],
                'kernel_blacklist': [],
                'nfs_blacklist': [],
                'lpae': False,
                'fastboot': False,
                'mach': 'qemu'}

apq8016_sbc = {'device_type': 'apq8016-sbc',
               'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                             'generic-uboot-tftp-ramdisk-kselftest-template.jinja2'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['allnoconfig',
                                       'allmodconfig',
                                       'defconfig+CONFIG_KASAN=y'],
               'kernel_blacklist': [],
               'nfs_blacklist': [],
               'lpae': False,
               'fastboot': True,
               'mach': 'qcom'}

apm_mustang = {'device_type': 'mustang',
               'templates': ['generic-uboot-tftp-ramdisk-template.jinja2',
                             'generic-uboot-tftp-ramdisk-kselftest-template.jinja2',
                             'generic-uboot-tftp-nfs-template.jinja2'],
               'kernel_defconfig_blacklist': [],
               'defconfig_blacklist': ['allnoconfig',
                                       'allmodconfig',
                                       'defconfig+CONFIG_RANDOMIZE_BASE=y'],
               'kernel_blacklist': [],
               'nfs_blacklist': ['v3.10',
                                 'lsk-v3.10',
                                 'v3.12',
                                 'v3.14',
                                 'lsk-v3.14',
                                 'v3.18'],
               'be_blacklist': ['v3.10'],
               'lpae': False,
               'fastboot': False,
               'mach': 'apm'}

apm_mustang_kvm = {'device_type': 'mustang',
                   'templates': ['generic-arm64-boot-kvm-template.json',
                                 'generic-arm64-boot-kvm-uefi-template.json'],
                   'kernel_defconfig_blacklist': [],
                   'defconfig_blacklist': ['allnoconfig',
                                           'allmodconfig'],
                   'kernel_blacklist': ['v3.10',
                                        'lsk-v3.10',
                                        'v3.12',
                                        'lsk-v3.12',
                                        'v3.14',
                                        'lsk-v3.14',
                                        'v3.18',
                                        'lsk-v3.18'],
                   'nfs_blacklist': [],
                   'lpae': False,
                   'fastboot': False,
                   'mach': 'apm'}

juno = {'device_type': 'juno',
        'templates': ['juno-arm64-dtb-kernel-ci-boot-template.json',
                      'generic-arm64-dtb-kernel-ci-boot-nfs-template.json',
                      'juno-arm64-dtb-kernel-ci-ltp-mm-template.json',
                      'juno-arm64-dtb-kernel-ci-kselftest-template.json'],
        'kernel_defconfig_blacklist': [],
        'defconfig_blacklist': ['allnoconfig',
                                'allmodconfig',
                                'defconfig+CONFIG_RANDOMIZE_BASE=y'],
        'kernel_blacklist': [],
        'nfs_blacklist': [],
        'lpae': False,
        'fastboot': False,
        'mach': 'arm'}

fvp_aemv8a = {'device_type': 'rtsm_fvp_base-aemv8a',
              'templates': ['generic-arm64-dtb-uefi-kernel-ci-boot-template.json',
                            'generic-arm64-dtb-kernel-ci-kselftest-template.json'],
              'kernel_defconfig_blacklist': [],
              'defconfig_blacklist': ['allnoconfig',
                                      'allmodconfig',
                                      'defconfig+kvm-host',
                                      'defconfig+kvm-guest'],
              'kernel_blacklist': [],
              'nfs_blacklist': [],
              'lpae': False,
              'fastboot': False,
              'mach': 'arm'}

juno_kvm = {'device_type': 'juno',
            'templates': ['generic-arm64-boot-kvm-template.json',
                          'generic-arm64-boot-kvm-uefi-template.json'],
            'kernel_defconfig_blacklist': [],
            'defconfig_blacklist': ['allnoconfig',
                                    'allmodconfig'],
            'kernel_blacklist': ['v3.10',
                                 'lsk-v3.10',
                                 'v3.12',
                                 'lsk-v3.12',
                                 'v3.14',
                                 'lsk-v3.14',
                                 'v3.18',
                                 'lsk-v3.18'],
            'nfs_blacklist': [],
            'lpae': False,
            'fastboot': False,
            'mach': 'arm'}

hi6220_hikey = {'device_type': 'hi6220-hikey',
                'templates': ['generic-arm64-dtb-kernel-ci-boot-template.json',
                              'generic-arm64-dtb-kernel-ci-kselftest-template.json',
                              'generic-arm64-uboot-dtb-kernel-ci-hackbench-template.json'],
                'kernel_defconfig_blacklist': [],
                'defconfig_blacklist': ['allnoconfig',
                                        'allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': [],
               'lpae': False,
               'fastboot': False,
               'mach': 'hisi'}

fsl_ls2080a_rdb = {'device_type': 'fsl-ls2085a-rdb',
                   'templates': ['generic-arm64-dtb-kernel-ci-boot-template.json',
                                 'generic-arm64-dtb-kernel-ci-boot-be-template.json',
                                 'generic-arm64-dtb-kernel-ci-kselftest-template.json',
                                 'generic-arm64-uboot-dtb-kernel-ci-hackbench-template.json'],
                   'kernel_defconfig_blacklist': [],
                   'defconfig_blacklist': ['allnoconfig',
                                           'allmodconfig'],
                   'kernel_blacklist': ['v4.1',
                                        'lsk-v4.1',
                                        'stable-queue-v4.1'],
                   'nfs_blacklist': [],
                   'lpae': False,
                   'fastboot': False,
                   'mach': 'freescale',
                   'boot_be': True}

fsl_ls2080a_simu = {'device_type': 'fsl-ls2085a-rdb',
                   'templates': ['generic-arm64-dtb-kernel-ci-boot-template.json',
                                 'generic-arm64-dtb-kernel-ci-boot-be-template.json',
                                 'generic-arm64-dtb-kernel-ci-kselftest-template.json',
                                 'generic-arm64-uboot-dtb-kernel-ci-hackbench-template.json'],
                   'kernel_defconfig_blacklist': [],
                   'defconfig_blacklist': ['allnoconfig',
                                           'allmodconfig'],
                   'kernel_blacklist': ['v4.1',
                                        'lsk-v4.1',
                                        'stable-queue-v4.1'],
                   'nfs_blacklist': [],
                   'lpae': False,
                   'fastboot': False,
                   'mach': 'freescale',
                   'boot_be': True}

x86 = {'device_type': 'x86',
       'templates': ['generic-x86-kernel-ci-boot-template.json',
                     'generic-x86-kernel-ci-kselftest-template.json',
                     'generic-x86-kernel-ci-hackbench-template.json'],
       'kernel_defconfig_blacklist': [],
       'defconfig_blacklist': ['i386_defconfig',
                               'allnoconfig',
                               'allmodconfig',
                               'allmodconfig+CONFIG_OF=n',
                               'tinyconfig',
                               'kvm_guest.config'],
       'kernel_blacklist': [],
       'nfs_blacklist': [],
       'lpae': False,
       'fastboot': False,
       'mach': 'x86'}

x86_pentium4 = {'device_type': 'x86-pentium4',
       'templates': ['generic-grub-tftp-ramdisk-template.jinja2',
                     'generic-grub-tftp-ramdisk-kselftest-template.jinja2',
                     'generic-grub-tftp-nfs-template.jinja2'],
       'kernel_defconfig_blacklist': [],
       'defconfig_blacklist': ['x86_64_defconfig',
                               'allnoconfig',
                               'allmodconfig',
                               'allmodconfig+CONFIG_OF=n',
                               'tinyconfig',
                               'kvm_guest.config'],
       'kernel_blacklist': [],
       'nfs_blacklist': [],
       'lpae': False,
       'fastboot': False,
       'mach': 'x86'}

x86_celeron = {'device_type': 'x86-celeron',
       'templates': ['generic-ipxe-tftp-ramdisk-template.jinja2',
                     'generic-ipxe-tftp-nfs-template.jinja2',
                     'generic-ipxe-tftp-ramdisk-simple-template.jinja2'],
       'kernel_defconfig_blacklist': [],
       'defconfig_blacklist': ['x86_64_defconfig',
                               'allnoconfig',
                               'allmodconfig',
                               'allmodconfig+CONFIG_OF=n',
                               'tinyconfig',
                               'kvm_guest.config'],
       'kernel_blacklist': [],
       'nfs_blacklist': [],
       'lpae': False,
       'fastboot': False,
       'mach': 'x86'}

x86_x5_z8350 = {'device_type': 'x86-x5-z8350',
       'templates': ['generic-grub-tftp-ramdisk-template.jinja2',
                     'generic-grub-tftp-nfs-template.jinja2'],
       'kernel_defconfig_blacklist': [],
       'defconfig_blacklist': ['i386_defconfig',
                               'allnoconfig',
                               'allmodconfig',
                               'allmodconfig+CONFIG_OF=n',
                               'tinyconfig',
                               'kvm_guest.config'],
       'kernel_blacklist': [],
       'nfs_blacklist': [],
       'lpae': False,
       'fastboot': False,
       'mach': 'x86'}

x86_atom330 = {'device_type': 'x86-atom330',
                         'templates': ['generic-ipxe-tftp-ramdisk-template.jinja2',
                                       'generic-ipxe-tftp-ramdisk-kselftest-template.jinja2',
                                       'generic-ipxe-tftp-nfs-template.jinja2',
                                       'generic-ipxe-tftp-ramdisk-simple-template.jinja2'],
                         'kernel_defconfig_blacklist': [],
                         'defconfig_blacklist': ['i386_defconfig',
                                                 'allnoconfig',
                                                 'allmodconfig',
                                                 'allmodconfig+CONFIG_OF=n',
                                                 'tinyconfig',
                                                 'kvm_guest.config'],
                         'kernel_blacklist': [],
                         'nfs_blacklist': [],
                         'lpae': False,
                         'fastboot': False,
                         'mach': 'x86'}

minnowboard_max_E3825 = {'device_type': 'minnowboard-max-E3825',
                         'templates': ['generic-x86-kernel-ci-boot-template.json',
                                       'generic-x86-kernel-ci-cyclictest-template.json',
                                       'generic-x86-kernel-ci-kselftest-template.json',
                                       'generic-x86-kernel-ci-hackbench-template.json',
                                       'generic-x86-kernel-ci-lmbench-template.json',
                                       'generic-x86-kernel-ci-ltp-realtime-template.json'],
                         'kernel_defconfig_blacklist': [],
                         'defconfig_blacklist': ['i386_defconfig',
                                                 'allnoconfig',
                                                 'allmodconfig',
                                                 'allmodconfig+CONFIG_OF=n',
                                                 'tinyconfig',
                                                 'kvm_guest.config'],
                         'kernel_blacklist': [],
                         'nfs_blacklist': [],
                         'lpae': False,
                         'fastboot': False,
                         'mach': 'x86'}

x86_kvm = {'device_type': 'kvm',
           'templates': ['generic-x86-kernel-ci-boot-template.json',
                         'generic-x86-kernel-ci-kselftest-template.json',
                         'generic-x86-kernel-ci-hackbench-template.json'],
           'kernel_defconfig_blacklist': [],
           'defconfig_blacklist': ['i386_defconfig',
                                   'allnoconfig',
                                   'allmodconfig',
                                   'allmodconfig+CONFIG_OF=n',
                                   'tinyconfig',
                                   'kvm_guest.config'],
           'kernel_blacklist': ['v3.10',
                                'lsk-v3.10'],
           'nfs_blacklist': [],
           'lpae': False,
           'fastboot': False,
           'mach': 'x86'}

qemu_i386 = {'device_type': 'qemu-i386',
             'templates': ['generic-x86-kernel-ci-boot-template.json',
                           'generic-x86-kernel-ci-kselftest-template.json',
                           'generic-x86-kernel-ci-hackbench-template.json'],
             'kernel_defconfig_blacklist': [],
             'defconfig_blacklist': ['x86_64_defconfig',
                                     'defconfig+CONFIG_LKDTM=y',
                                     'defconfig+CONFIG_OF_UNITTEST=y',
                                     'defconfig+kvm_guest',
                                     'allnoconfig',
                                     'allmodconfig',
                                     'allmodconfig+CONFIG_OF=n',
                                     'tinyconfig',
                                     'kvm_guest.config'],
             'kernel_blacklist': ['v3.10',
                                  'lsk-v3.10'],
             'nfs_blacklist': [],
             'lpae': False,
             'fastboot': False,
             'mach': 'qemu'}

imx6dl_riotboard = {'device_type': 'imx6dl-riotboard',
                    'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                  'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                                  'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                                  'generic-arm-dtb-kernel-ci-kselftest-template.json',
                                  'generic-arm-dtb-kernel-ci-hackbench-template.json'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['imx_v4_v5_defconfig',
                                            'multi_v5_defconfig',
                                            'allmodconfig',
                                            'multi_v7_defconfig+CONFIG_EFI=y'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'imx'}

imx53_qsbr = {'device_type': 'imx53-qsbr',
              'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                            'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                            'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                            'generic-arm-dtb-kernel-ci-kselftest-template.json',
                            'generic-arm-dtb-kernel-ci-hackbench-template.json'],
              'kernel_defconfig_blacklist': [],
              'defconfig_blacklist': ['imx_v4_v5_defconfig',
                                      'multi_v5_defconfig',
                                      'allmodconfig',
                                      'multi_v7_defconfig+CONFIG_EFI=y'],
              'kernel_blacklist': [],
              'nfs_blacklist': [],
              'lpae': False,
              'fastboot': False,
              'mach': 'imx'}

imx28_duckbill = {'device_type': 'imx28-duckbill',
                  'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                  'kernel_defconfig_blacklist': [],
                  'defconfig_blacklist': ['allmodconfig'],
                  'kernel_blacklist': ['v3.',
                                       'v4.0',
                                       'v4.1',
                                       'v4.2',
                                       'v4.3',
                                       'v4.4',
                                       'v4.5'],
                  'nfs_blacklist': [],
                  'lpae': False,
                  'fastboot': False,
                  'mach': 'imx'}

imx23_olinuxino = {'device_type': 'imx23-olinuxino',
                   'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                   'kernel_defconfig_blacklist': [],
                   'defconfig_blacklist': ['allmodconfig'],
                   'kernel_blacklist': ['v3.',
                                        'v4.0',
                                        'v4.1',
                                        'v4.2',
                                        'v4.3',
                                        'v4.4',
                                        'v4.5'],
                   'nfs_blacklist': [],
                   'lpae': False,
                   'fastboot': False,
                   'mach': 'imx'}

socfpga_cyclone5_socrates = {'device_type': 'socfpga-cyclone5-socrates',
                             'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                           'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                                           'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                                           'generic-arm-dtb-kernel-ci-kselftest-template.json',
                                           'generic-arm-dtb-kernel-ci-hackbench-template.json'],
                             'kernel_defconfig_blacklist': [{'kernel_version': 'v4.5', 'defconfig': 'socfpga_defconfig'},
                                                            {'kernel_version': 'v4.4', 'defconfig': 'socfpga_defconfig'},
                                                            {'kernel_version': 'v4.3', 'defconfig': 'socfpga_defconfig'},
                                                            {'kernel_version': 'v4.2', 'defconfig': 'socfpga_defconfig'},
                                                            {'kernel_version': 'v4.1', 'defconfig': 'socfpga_defconfig'},
                                                            {'kernel_version': 'v4.0', 'defconfig': 'socfpga_defconfig'},
                                                            {'kernel_version': 'v3.', 'defconfig': 'socfpga_defconfig'}],
                             'defconfig_blacklist': ['allmodconfig',
                                                     'multi_v7_defconfig+CONFIG_EFI=y'],
                             'kernel_blacklist': [],
                             'nfs_blacklist': [],
                             'lpae': False,
                             'fastboot': False,
                             'mach': 'socfpga'}

imx27_phycard_s = {'device_type': 'imx27-phytec-phycard-s-rdk',
                   'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                   'kernel_defconfig_blacklist': [],
                   'defconfig_blacklist': ['allmodconfig'],
                   'kernel_blacklist': ['v3.',
                                        'v4.0',
                                        'v4.1',
                                        'v4.2',
                                        'v4.3',
                                        'v4.4',
                                        'v4.5',
                                        'v4.6'],
                   'nfs_blacklist': [],
                   'lpae': False,
                   'fastboot': False,
                   'mach': 'imx'}

openblocks_ax3 = {'device_type': 'armada-xp-openblocks-ax3-4',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig',
                                            'multi_v7_defconfig+CONFIG_SMP=n'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'mvebu'}

openblocks_a7 = {'device_type': 'kirkwood-openblocks_a7',
                 'templates': ['generic-uboot-tftp-nfs-template.jinja2'],
                 'kernel_defconfig_blacklist': [],
                 'defconfig_blacklist': ['allmodconfig',
		 # To be removed once NFS is working for this defconfig
					 'multi_v5_defconfig'],
                 'kernel_blacklist': ['v3'],
                 'nfs_blacklist': [],
                 'lpae': False,
                 'fastboot': False,
                 'mach': 'mvebu'}

armada_xp_linksys_mamba = {'device_type': 'armada-xp-linksys-mamba',
			   'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
			   'kernel_defconfig_blacklist': [],
			   'defconfig_blacklist': ['allmodconfig',
						   'multi_v7_defconfig+CONFIG_SMP=n'],
			   'kernel_blacklist': [],
			   'nfs_blacklist': [],
			   'lpae': False,
			   'fastboot': False,
               'mach': 'mvebu'}

armada_388_clearfog = {'device_type': 'armada-388-clearfog',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig',
                                            'multi_v7_defconfig+CONFIG_SMP=n'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'mvebu'}

chip_pro = {'device_type': 'sun5i-gr8-chip-pro',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig',
                                            'multi_v7_defconfig+CONFIG_LKDTM=y'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'sunxi'}

chip = {'device_type': 'sun5i-r8-chip',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'sunxi'}

imx6q_nitrogen6x = {'device_type': 'imx6q-nitrogen6x',
                   'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                   'kernel_defconfig_blacklist': [],
                   'defconfig_blacklist': ['allmodconfig',
					   'imx_v4_v5_defconfig',
					   'multi_v5_defconfig'],
                   'kernel_blacklist': [],
                   'nfs_blacklist': [],
                   'lpae': False,
                   'fastboot': False,
                   'mach': 'imx'}

sama5d34ek = {'device_type': 'sama5d34ek',
                    'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig',
					    'at91_dt_defconfig',
					    'at91rm9200_defconfig',
					    'at91sam9261_9g10_defconfig',
					    'at91sam9263_defconfig',
					    'at91sam9g45_defconfig',
					    'at91sam9rl_defconfig',
					    'at91x40_defconfig',
					    'at91sam9260_9g20_defconfig',
					    'at91sam9260_defconfig',
					    'at91sam9261_defconfig',
					    'at91sam9g20_defconfig',
					    'at91sam9rl_defconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'at91'}

sama5d36ek = {'device_type': 'sama5d36ek',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig',
					    'at91_dt_defconfig',
					    'at91rm9200_defconfig',
					    'at91sam9261_9g10_defconfig',
					    'at91sam9263_defconfig',
					    'at91sam9g45_defconfig',
					    'at91sam9rl_defconfig',
					    'at91x40_defconfig',
					    'at91sam9260_9g20_defconfig',
					    'at91sam9260_defconfig',
					    'at91sam9261_defconfig',
					    'at91sam9g20_defconfig',
					    'at91sam9rl_defconfig',
                        'multi_v7_defconfig+CONFIG_PROVE_LOCKING=y'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'at91'}

sama5d35ek = {'device_type': 'sama5d35ek',
                    'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig',
					    'at91_dt_defconfig',
					    'at91rm9200_defconfig',
					    'at91sam9261_9g10_defconfig',
					    'at91sam9263_defconfig',
					    'at91sam9g45_defconfig',
					    'at91sam9rl_defconfig',
					    'at91x40_defconfig',
					    'at91sam9260_9g20_defconfig',
					    'at91sam9260_defconfig',
					    'at91sam9261_defconfig',
					    'at91sam9g20_defconfig',
					    'at91sam9rl_defconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'at91'}

at91sam9m10g45ek = {'device_type': 'at91sam9m10g45ek',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig',
					    'multi_v7_defconfig',
					    'at91rm9200_defconfig',
					    'at91sam9261_9g10_defconfig',
					    'at91sam9263_defconfig',
					    'at91sam9rl_defconfig',
					    'at91x40_defconfig',
					    'sama5_defconfig',
					    'at91sam9260_9g20_defconfig',
					    'at91sam9260_defconfig',
					    'at91sam9261_defconfig',
					    'at91sam9g20_defconfig',
					    'at91sam9rl_defconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'at91'}

sam9261ek = {'device_type': 'at91sam9261ek',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig',
					    'multi_v7_defconfig',
					    'at91rm9200_defconfig',
					    'at91sam9263_defconfig',
					    'at91sam9g45_defconfig',
					    'at91sam9rl_defconfig',
					    'at91x40_defconfig',
					    'sama5_defconfig',
					    'at91sam9260_9g20_defconfig',
					    'at91sam9260_defconfig',
					    'at91sam9g20_defconfig',
					    'at91sam9rl_defconfig'],
                    'kernel_blacklist': ['v3.'],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'at91'}

sam9x25ek = {'device_type': 'at91sam9x25ek',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig',
					    'multi_v7_defconfig',
					    'at91rm9200_defconfig',
					    'at91sam9261_9g10_defconfig',
					    'at91sam9263_defconfig',
					    'at91sam9g45_defconfig',
					    'at91sam9rl_defconfig',
					    'at91x40_defconfig',
					    'sama5_defconfig',
					    'at91sam9260_9g20_defconfig',
					    'at91sam9260_defconfig',
					    'at91sam9261_defconfig',
					    'at91sam9g20_defconfig',
					    'at91sam9rl_defconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'at91'}

at91sam9x35ek = {'device_type': 'at91sam9x35ek',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig',
					    'multi_v7_defconfig',
					    'at91rm9200_defconfig',
					    'at91sam9261_9g10_defconfig',
					    'at91sam9263_defconfig',
					    'at91sam9g45_defconfig',
					    'at91sam9rl_defconfig',
					    'at91x40_defconfig',
					    'sama5_defconfig',
					    'at91sam9260_9g20_defconfig',
					    'at91sam9260_defconfig',
					    'at91sam9261_defconfig',
					    'at91sam9g20_defconfig',
					    'at91sam9rl_defconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'at91'}

at91rm9200ek = {'device_type': 'at91rm9200ek',
                    'templates': ['generic-uboot-tftp-nfs-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig'],
                    'kernel_blacklist': ['v3'],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'at91'}

at91_sama5d2_xplained = {'device_type': 'at91-sama5d2_xplained',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'at91'}

at91_sama5d4_xplained = {'device_type': 'at91-sama5d4_xplained',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'at91'}

sun8i_a23_evb = {'device_type': 'sun8i-a23-evb',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'sunxi'}

sun8i_a83t_allwinner_h8homlet_v2 = {'device_type': 'sun8i-a83t-allwinner-h8homlet-v2',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'sunxi'}

sun8i_h3_orangepi_pc = {'device_type': 'sun8i-h3-orangepi-pc',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'sunxi'}

sinlinx_sina33 = {'device_type': 'sun8i-a33-sinlinx-sina33',
                    'templates': ['generic-uboot-tftp-ramdisk-template.jinja2'],
                    'kernel_defconfig_blacklist': [],
                    'defconfig_blacklist': ['allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False,
                    'mach': 'sunxi'}

dove_cubox = {'device_type': 'dove-cubox',
                       'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                       'kernel_defconfig_blacklist': [],
                       'defconfig_blacklist': ['allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False,
                       'mach': 'mvebu'}

device_map = {'alpine-db.dtb': [alpine_db],
              'alpine-v2-evp.dtb': [alpine_v2_evp],
              'bcm2835-rpi-b-plus.dtb': [bcm2835_rpi_b_plus],
              'bcm2836-rpi-2-b.dtb' : [ bcm2836_rpi_2_b],
              'bcm2837-rpi-3-b.dtb' : [ bcm2837_rpi_3_b, bcm2837_rpi_3_b_32],
              'bcm4708-smartrg-sr400ac.dtb': [bcm4708_smartrg_sr400ac],
              'armada-370-db.dtb': [armada_370_db],
              'armada-370-mirabox.dtb': [armada_370_mirabox],
              'orion5x-rd88f5182-nas.dtb': [orion5x_rd88f5182_nas],
              'armada-370-rd.dtb': [armada_370_rd],
              'armada-375-db.dtb': [armada_375_db],
              'armada-385-db-ap.dtb': [armada_385_db_ap],
              'armada-388-gp.dtb': [armada_388_gp],
              'armada-398-db.dtb': [armada_398_db],
              'kirkwood-db-88f6282.dtb': [kirkwood_db_88f6282],
              'armada-3720-db.dtb': [armada_3720_db],
              'armada-7040-db.dtb': [armada_7040_db],
              'armada-8040-db.dtb': [armada_8040_db],
              'armada-xp-db.dtb': [armada_xp_db],
              'armada-xp-gp.dtb': [armada_xp_gp],
              'exynos5250-arndale.dtb': [arndale],
              'exynos5250-snow.dtb': [snow],
              'exynos5420-arndale-octa.dtb': [arndale_octa],
              'exynos5800-peach-pi.dtb': [peach_pi],
              'exynos5422-odroidxu3.dtb': [odroid_xu3],
              'exynos4412-odroidu3.dtb': [odroid_u2],
              'exynos4412-odroidx2.dtb': [odroid_x2],
              'am335x-boneblack.dtb': [beaglebone_black],
              'omap3-beagle-xm.dtb': [beagle_xm],
              'omap3-overo-tobi.dtb': [omap3_overo_tobi],
              'omap3-overo-storm-tobi.dtb': [omap3_overo_storm_tobi],
              'omap4-panda-es.dtb': [panda_es],
              'omap4-panda.dtb': [panda],
              'omap5-uevm.dtb' : [omap5_uevm],
              'dra7-evm.dtb' : [dra7_evm],
              'sun7i-a20-cubieboard2.dtb': [cubieboard2],
              'sun7i-a20-cubietruck.dtb': [cubieboard3, cubieboard3_kvm],
              'sun7i-a20-bananapi.dtb': [sun7i_a20_bananapi],
              'hip04-d01.dtb': [d01],
              'hip06-d03.dtb': [d03],
              'hip07-d05.dtb': [d05],
              'hisi-x5hd2-dkb.dtb': [hisi_x5hd2_dkb],
              'imx6ul-pico-hobbit.dtb': [imx6ul_pico_hobbit],
              'imx6q-wandboard.dtb': [imx6q_wandboard],
              'imx6q-sabrelite.dtb': [imx6q_sabrelite],
              'imx6q-cm-fx6.dtb': [utilite_pro],
              'meson8b-odroidc1.dtb': [meson8b_odroidc1],
              'meson-gxbb-odroidc2.dtb': [meson_gxbb_odroidc2],
              'meson-gxbb-p200.dtb': [meson_gxbb_p200],
              'meson-gxl-s905x-khadas-vim.dtb': [meson_gxl_s905x_khadas_vim],
              'r8a7795-salvator-x.dtb': [r8a7795_salvator_x],
              'r8a7796-m3ulcb.dtb': [r8a7796_m3ulcb],
              'da850-lcdk.dtb': [da850_lcdk],
              'ste-snowball.dtb': [snowball],
              'qcom-apq8084-ifc6540.dtb': [ifc6540],
              'qcom-apq8064-ifc6410.dtb': [ifc6410],
              'highbank.dtb': [highbank],
              'at91-sama5d3_xplained.dtb': [sama53d],
              'tegra124-jetson-tk1.dtb': [jetson_tk1],
              'tegra124-nyan-big.dtb': [tegra124_nyan_big],
              'zynq-parallella.dtb': [parallella],
              'zynq-zc702.dtb': [zynq_zc702],
              'sun9i-a80-optimus.dtb': [optimus_a80],
              'sun9i-a80-cubieboard4.dtb': [cubieboard4],
              'rk3288-rock2-square.dtb': [rk3288_rock2_square],
              'rk3288-veyron-jaq.dtb': [rk3288_veyron_jaq],
              'rk3399-gru-kevin.dtb': [rk3399_gru_kevin],
              'rk3399-puma-haikou.dtb': [rk3399_puma_haikou],
#              'zx296702-ad1.dtb': [zx296702_ad1],
              'vexpress-v2p-ca15-tc1.dtb': [qemu_arm_cortex_a15],
              'vexpress-v2p-ca15-tc1-legacy': [qemu_arm_cortex_a15_legacy],
              'vexpress-v2p-ca15_a7.dtb': [qemu_arm_cortex_a15_a7],
              'vexpress-v2p-ca9.dtb': [qemu_arm_cortex_a9],
              'vexpress-v2p-ca9-legacy': [qemu_arm_cortex_a9_legacy],
              'qemu-aarch64-legacy': [qemu_aarch64],
              'qemu': [qemu],
              'apq8016-sbc.dtb': [apq8016_sbc],
              'apm-mustang.dtb': [apm_mustang, apm_mustang_kvm],
              'juno.dtb': [juno, juno_kvm],
              'fvp-base-gicv2-psci.dtb': [fvp_aemv8a],
              'hi6220-hikey.dtb': [hi6220_hikey],
              'fsl-ls2080a-simu.dtb': [fsl_ls2080a_simu],
              'fsl-ls2080a-rdb.dtb': [fsl_ls2080a_rdb],
              'x86': [x86, minnowboard_max_E3825, x86_atom330, x86_x5_z8350],
              'x86-32': [x86_pentium4, x86_celeron],
              'x86-kvm': [x86_kvm],
              'qemu-i386': [qemu_i386],
              'imx6dl-riotboard.dtb': [imx6dl_riotboard],
              'imx53-qsrb.dtb': [imx53_qsbr],
              'imx28-duckbill.dtb': [imx28_duckbill],
              'imx23-olinuxino.dtb': [imx23_olinuxino],
              'socfpga_cyclone5_socrates.dtb': [socfpga_cyclone5_socrates],
              'imx27-phytec-phycard-s-rdk.dtb': [imx27_phycard_s],
              'armada-xp-linksys-mamba.dtb': [armada_xp_linksys_mamba],
              'armada-388-clearfog.dtb': [armada_388_clearfog],
              'sun5i-gr8-chip-pro.dtb': [chip_pro],
              'sun5i-r8-chip.dtb': [chip],
              'imx6q-nitrogen6x.dtb': [imx6q_nitrogen6x],
              'sama5d34ek.dtb': [sama5d34ek],
              'sama5d36ek.dtb': [sama5d36ek],
              'sama5d35ek.dtb': [sama5d35ek],
              'at91sam9261ek.dtb': [sam9261ek],
              'at91sam9x25ek.dtb': [sam9x25ek],
              'at91sam9x35ek.dtb': [at91sam9x35ek],
              'at91rm9200ek.dtb': [at91rm9200ek],
              'at91-sama5d2_xplained.dtb': [at91_sama5d2_xplained],
              'at91-sama5d4_xplained.dtb': [at91_sama5d4_xplained],
              'at91sam9m10g45ek.dtb': [at91sam9m10g45ek],
              'sun8i-a23-evb.dtb': [sun8i_a23_evb],
              'sun8i-a83t-allwinner-h8homlet-v2.dtb': [sun8i_a83t_allwinner_h8homlet_v2],
              'sun8i-h3-orangepi-pc.dtb': [sun8i_h3_orangepi_pc],
              'sun8i-a33-sinlinx-sina33.dtb': [sinlinx_sina33],
              'kirkwood-openblocks_a7.dtb': [openblocks_a7],
              'armada-xp-openblocks-ax3-4.dtb': [openblocks_ax3],
              'vf610-zii-dev-rev-b.dtb': [vf610_zii_dev_rev_b],
              'dove-cubox.dtb' : [dove_cubox],
              'r8a7791-porter.dtb': [r8a7791_porter]}
