---

- name: Make sure celery run directory exists
  file: path=/var/run/celery
        state=directory
        owner={{ app_user }}
        group={{ app_user }}
  tags:
    - init

- name: Install Upstart conf
  template: src=kernel-ci-backend.conf
            dest=/etc/init/{{ init_service }}.conf
            mode=0644
            owner=root
            group=root
  when: ansible_lsb.id == "Ubuntu"
  tags:
    - init
    - upstart

- name: Install kernelci systemd service
  template: src=kernelci-backend.service
            dest=/etc/systemd/system/{{ init_service }}.service
            mode=0644
            owner=root
            group=root
  when: ansible_lsb.id == "Debian"
  notify:
    - reload-systemd
  tags:
    - init
    - systemd

- name: Enable kernelci systemd service
  command:  /bin/systemctl enable {{ init_service }}.service
            creates=/etc/systemd/system/multi-user.target.wants/{{ init_service }}.service
  when: ansible_lsb.id == "Debian"
  tags:
    - init
    - systemd

- name: Install celery upstart configuration
  template: src=celery.conf
            dest=/etc/init/kernelci-celery.conf
            owner=root
            group=root
            mode=0644
  when: ansible_lsb.id == "Ubuntu"
  tags:
    - init
    - upstart

- name: Install celery systemd service
  template: src=kernelci-celery.service
            dest=/etc/systemd/system/kernelci-celery.service
            owner=root
            group=root
            mode=0644
  when: ansible_lsb.id == "Debian"
  tags:
    - init
    - systemd

- name: Install celery beat upstart configuration
  template: src=kernelci-celery-beat.conf
            dest=/etc/init/kernelci-celery-beat.conf
            owner=root
            group=root
            mode=0644
  when: ansible_lsb.id == "Ubuntu"
  tags:
    - init
    - upstart

- name: Install celery beat systemd service
  template: src=kernelci-celery-beat.service
            dest=/etc/systemd/system/kernelci-celery-beat.service
            owner=root
            group=root
            mode=0644
  when: ansible_lsb.id == "Debian"
  tags:
    - init
    - systemd

- name: Enable celery systemd service
  command:  /bin/systemctl enable kernelci-celery.service
            creates=/etc/systemd/system/multi-user.target.wants/kernelci-celery.service
  when: ansible_lsb.id == "Debian"
  notify:
    - reload-systemd
  tags:
    - init
    - systemd

- name: Enable celery beat systemd service
  command:  /bin/systemctl enable kernelci-celery-beat.service
            creates=/etc/systemd/system/multi-user.target.wants/kernelci-celery-beat.service
  when: ansible_lsb.id == "Debian"
  notify:
    - reload-systemd
  tags:
    - init
    - systemd

