db_configs:

  chromeos.kernelci.org:
    db_type: kernelci_backend
    url: https://api.chromeos.kernelci.org/

  kernelci.org:
    db_type: kernelci_backend
    url: https://api.kernelci.org/

  localhost:
    db_type: kernelci_backend
    url: http://localhost:5001/

  staging.kernelci.org:
    db_type: kernelci_backend
    url: https://api.staging.kernelci.org/


storage_configs:

  early-access-azure:
    storage_type: azure
    base_url: https://kciapistagingstorage1.file.core.windows.net/
    share: early-access
    sas_public_token: "?sv=2022-11-02&ss=bfqt&srt=sco&sp=r&se=2123-07-20T22:00:00Z&st=2023-07-21T18:27:25Z&spr=https&sig=TDt3NorDXylmyUtBQnP1S5BZ3uywR06htEGTG%2BSxLWg%3D"

  kernelci.org:
    storage_type: backend
    host: kernelci.org
    base_url: http://storage.kernelci.org/
    api_url: https://api.kernelci.org

  staging.kernelci.org:
    storage_type: backend
    host: staging.kernelci.org
    base_url: http://storage.staging.kernelci.org/
    api_url: https://api.staging.kernelci.org
