db_configs:

  chromeos.kernelci.org:
    db_type: kernelci_backend
    url: https://api.chromeos.kernelci.org/

  kernelci.org:
    db_type: kernelci_backend
    url: https://api.kernelci.org/

  localhost:
    db_type: kernelci_backend
    url: http://localhost:5001/

  staging.kernelci.org:
    db_type: kernelci_backend
    url: https://api.staging.kernelci.org/


storage_configs:

  chromeos.kernelci.org:
    storage_type: backend
    host: chromeos.kernelci.org
    base_url: http://storage.chromeos.kernelci.org/
    api_url: https://api.chromeos.kernelci.org

  kernelci.org:
    storage_type: backend
    host: kernelci.org
    base_url: http://storage.kernelci.org/
    api_url: https://api.kernelci.org

  staging.kernelci.org:
    storage_type: backend
    host: staging.kernelci.org
    base_url: http://storage.staging.kernelci.org/
    api_url: https://api.staging.kernelci.org
