runtimes:

  docker:
    lab_type: docker
    env_file: '.docker-env'

  # ToDo: also run jobs with callbacks sent to BayLibre's KernelCI backend
  lab-baylibre:
    lab_type: legacy.lava_xmlrpc
    url: 'https://lava.baylibre.com/RPC2/'
    queue_timeout:
      days: 1
    filters:
      - regex: {'tree': '^(kernelci|mainline|next|stable|arm64|riscv|soc|amlogic|matthiasbgg)$'}
      - passlist:
          plan:
            - baseline
            - kselftest
            - preempt-rt
            - ltp

  lab-broonie:
    lab_type: legacy.lava_xmlrpc
    url: 'https://lava.sirena.org.uk/RPC2/'
    priority_min: 0
    priority_max: 40
    queue_timeout:
      days: 1
    filters:
      - blocklist: {tree: [android]}

  lab-cip:
    lab_type: legacy.lava_xmlrpc
    url: 'https://lava.ciplatform.org/RPC2/'
    priority: low
    filters:
      - passlist:
          plan:
            - baseline
            - baseline-cip-nfs
            - baseline-nfs
            - kselftest
            - ltp
            - preempt-rt
            - smc
      - combination:
          keys: ['tree', 'branch']
          values:
            - ['cip', 'linux-4.4.y-cip']
            - ['cip', 'linux-4.4.y-cip-rt']
            - ['cip-gitlab', 'ci/iwamatsu/linux-4.4.y-cip-rc']
            - ['cip', 'linux-4.19.y-cip']
            - ['cip', 'linux-4.19.y-cip-rt']
            - ['cip-gitlab', 'ci/iwamatsu/linux-4.19.y-cip-rc']
            - ['cip', 'linux-5.10.y-cip']
            - ['cip', 'linux-5.10.y-cip-rt']
            - ['cip-gitlab', 'ci/iwamatsu/linux-5.10.y-cip-rc']
            - ['cip-gitlab', 'ci/pavel/linux-test']
            - ['kernelci', 'staging-cip']
            - ['mainline', 'master']
            - ['next', 'master']
            - ['next', 'pending-fixes']
            - ['renesas', 'master']
            - ['renesas-next', 'next']
            - ['stable', 'linux-4.4.y']
            - ['stable', 'linux-4.19.y']
            - ['stable', 'linux-5.10.y']
            - ['stable-rc', 'linux-4.4.y']
            - ['stable-rc', 'linux-4.19.y']
            - ['stable-rc', 'linux-5.10.y']

  lab-clabbe:
    lab_type: legacy.lava_xmlrpc
    url: 'https://lava.montjoie.ovh/RPC2/'
    queue_timeout:
      hours: 24
    filters:
      - passlist:
          plan:
            - baseline
            - sleep
          tree:
            - kernelci
            - mainline
            - next
            - stable-rc
            - stable

  lab-collabora:
    lab_type: legacy.lava_rest
    url: 'https://lava.collabora.dev/'
    priority: 45
    queue_timeout:
      days: 2
    filters: &collabora-filters
      - blocklist:
          tree: [android]

  lab-collabora-staging:
    lab_type: legacy.lava_rest
    url: 'https://staging.lava.collabora.dev/'
    priority: 45
    queue_timeout:
      hours: 1
    filters: *collabora-filters

  lab-kontron:
    lab_type: legacy.lava_rest
    url: 'https://lavalab.kontron.com/'
    filters:
      - passlist:
          plan:
            - baseline

  lab-linaro-lkft:
    lab_type: legacy.lava_rest
    url: 'https://lkft.validation.linaro.org/'
    priority_min: 0
    priority_max: 25
    queue_timeout:
      days: 1
    filters:
      - passlist:
          plan:
            - baseline
            - kselftest
            - ltp
          tree:
            - kernelci
            - next
            - stable-rc
            - stable

  lab-nxp:
    lab_type: legacy.lava_rest
    url: 'https://lavalab.nxp.com/'
    filters:
      - passlist:
          plan:
            - baseline

  lab-pengutronix:
    lab_type: legacy.lava_rest
    url: 'https://hekla.openlab.pengutronix.de/'
    filters:
      - passlist:
          plan:
            - baseline

  lab-theobroma-systems:
    lab_type: legacy.lava_xmlrpc
    url: 'https://lava.theobroma-systems.com/RPC2/'
    filters:
      - passlist:
          plan:
            - baseline

  shell:
    lab_type: shell
