storage:

  early-access-azure:
    storage_type: azure
    base_url: https://kciapistagingstorage1.file.core.windows.net/
    share: early-access
    sas_public_token: "?sv=2022-11-02&ss=f&srt=sco&sp=r&se=2024-10-17T19:19:12Z&st=2023-10-17T11:19:12Z&spr=https&sig=sLmFlvZHXRrZsSGubsDUIvTiv%2BtzgDq6vALfkrtWnv8%3D"

  kernelci.org:
    storage_type: backend
    host: kernelci.org
    base_url: http://storage.kernelci.org/
    api_url: https://api.kernelci.org

  staging.kernelci.org:
    storage_type: backend
    host: staging.kernelci.org
    base_url: http://storage.staging.kernelci.org/
    api_url: https://api.staging.kernelci.org
