# This is LEGACY system config, do not send any new patches for this file.
# More details:
# https://lore.kernel.org/kernelci/5b603b8f-c9b2-4148-7212-dd69a3fdf506@collabora.com/T/#u

file_system_types:

  buildroot: &buildroot
    url: 'http://storage.kernelci.org/images/rootfs/buildroot'

    arch_map:
      arm64be: [{arch: arm64, endian: big}]
      armeb:   [{arch: arm,   endian: big}]
      armel:   [{arch: arm}]
      x86:     [{arch: i386}, {arch: x86_64}]
      mipsel:  [{arch: mips}]

  buildroot-staging:
    <<: *buildroot
    url: 'http://storage.staging.kernelci.org/images/rootfs/buildroot'

  debian: &debian
    url: 'http://storage.kernelci.org/images/rootfs/debian'
    arch_map:
      armel: [{arch: arm, variant: v4t},
              {arch: arm, variant: v5},
              {arch: arm, variant: v6}]
      armhf: [{arch: arm}]
      amd64: [{arch: x86_64}]
      riscv64: [{arch: riscv}]

  # Convenience to test new rootfs images on staging.kernelci.org
  debian-staging:
    <<: *debian
    url: 'http://storage.staging.kernelci.org/images/rootfs/debian'


