@Library('kernelci') _

buildImage {

    name = 'stretch'
    archList = ["armhf", "armel", "arm64", "x86", "x86_64", "mips", "mipsel", "mips64el"]

    //Extra packages to be installed in the image
    //extra_packages = ""

}
